# Generated by Django 2.0.1 on 2018-05-03 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prefixes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefix',
            name='company_organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company_organisations.CompanyOrganisation'),
        ),
    ]
