# Generated by Django 2.0.1 on 2018-05-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prefixes', '0002_auto_20180503_1006'),
        ('prefixes', '0002_auto_20180504_0323'),
    ]

    operations = [
    ]
