# Generated by Django 2.0.1 on 2018-05-04 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prefixes', '0003_merge_20180504_0822'),
        ('prefixes', '0002_typo_in_MemberOrganisation'),
    ]

    operations = [
    ]
