# Generated by Django 2.0.1 on 2018-05-24 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prefixes', '0004_merge_20180504_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prefix',
            name='is_active',
        ),
    ]
