# Generated by Django 2.0.1 on 2018-05-24 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prefixes', '0005_remove_prefix_is_active'),
        ('users', '0002_auto_20180512_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='product_active_prefix',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prefixes.Prefix'),
        ),
    ]
