# Generated by Django 2.0.1 on 2018-05-24 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_product_active_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agreed_bacode_disclaimer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='agreed_bacode_disclaimer_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
