# Generated by Django 2.0.1 on 2018-05-25 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180524_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='product_active_prefix',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='prefixes.Prefix'),
        ),
    ]
