# Generated by Django 2.0.1 on 2018-05-26 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180525_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='member_organisation',
            field=models.ForeignKey(default=7, null=True, on_delete=django.db.models.deletion.CASCADE, to='member_organisations.MemberOrganisation'),
        ),
    ]
