# Generated by Django 2.0.1 on 2018-06-12 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180526_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='agreed_bacode_disclaimer',
            new_name='agreed_barcode_disclaimer',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='agreed_bacode_disclaimer_date',
            new_name='agreed_barcode_disclaimer_date',
        ),
    ]
