# -*- coding: utf-8 -*-
LANGUAGES = (
    (u"ab", u"Abkhaz"),
    (u"aa", u"Afar"),
    (u"af", u"Afrikaans"),
    (u"ak", u"Akan"),
    (u"sq", u"Albanian"),
    (u"am", u"Amharic"),
    (u"ar", u"Arabic"),
    (u"an", u"Aragonese"),
    (u"hy", u"Armenian"),
    (u"as", u"Assamese"),
    (u"av", u"Avaric"),
    (u"ae", u"Avestan"),
    (u"ay", u"Aymara"),
    (u"az", u"Azerbaijani"),
    (u"bm", u"Bambara"),
    (u"ba", u"Bashkir"),
    (u"eu", u"Basque"),
    (u"be", u"Belarusian"),
    (u"bh", u"Bihari"),
    (u"bi", u"Bislama"),
    (u"bs", u"Bosnian"),
    (u"br", u"Breton"),
    (u"bg", u"Bulgarian"),
    (u"my", u"Burmese"),
    (u"ca", u"Catalan, Valencian"),
    (u"ch", u"Chamorro"),
    (u"ce", u"Chechen"),
    (u"zh", u"Chinese"),
    (u"cv", u"Chuvash"),
    (u"kw", u"Cornish"),
    (u"co", u"Corsican"),
    (u"cr", u"Cree"),
    (u"hr", u"Croatian"),
    (u"cs", u"Czech"),
    (u"da", u"Danish"),
    (u"nl", u"Dutch"),
    (u"dz", u"Dzongkha"),
    (u"en", u"English"),
    (u"eo", u"Esperanto"),
    (u"et", u"Estonian"),
    (u"ee", u"Ewe"),
    (u"fo", u"Faroese"),
    (u"fj", u"Fijian"),
    (u"fi", u"Finnish"),
    (u"fr", u"French"),
    (u"gl", u"Galician"),
    (u"ka", u"Georgian"),
    (u"de", u"German"),
    (u"el", u"Greek, Modern"),
    (u"gn", u"Guarani"),
    (u"gu", u"Gujarati"),
    (u"ht", u"Haitian, Haitian Creole"),
    (u"he", u"Hebrew (modern)"),
    (u"hz", u"Herero"),
    (u"hi", u"Hindi"),
    (u"ho", u"Hiri Motu"),
    (u"hu", u"Hungarian"),
    (u"ia", u"Interlingua"),
    (u"id", u"Indonesian"),
    (u"ie", u"Interlingue"),
    (u"ga", u"Irish"),
    (u"ig", u"Igbo"),
    (u"ik", u"Inupiaq"),
    (u"io", u"Ido"),
    (u"is", u"Icelandic"),
    (u"it", u"Italian"),
    (u"iu", u"Inuktitut"),
    (u"ja", u"Japanese"),
    (u"jv", u"Javanese"),
    (u"kl", u"Kalaallisut, Greenlandic"),
    (u"kn", u"Kannada"),
    (u"kr", u"Kanuri"),
    (u"ks", u"Kashmiri"),
    (u"kk", u"Kazakh"),
    (u"km", u"Khmer"),
    (u"ki", u"Kikuyu, Gikuyu"),
    (u"rw", u"Kinyarwanda"),
    (u"ky", u"Kyrgyz"),
    (u"kv", u"Komi"),
    (u"kg", u"Kongo"),
    (u"ko", u"Korean"),
    (u"ku", u"Kurdish"),
    (u"kj", u"Kwanyama, Kuanyama"),
    (u"la", u"Latin"),
    (u"lb", u"Luxembourgish, Letzeburgesch"),
    (u"lg", u"Ganda"),
    (u"li", u"Limburgish, Limburgan, Limburger"),
    (u"ln", u"Lingala"),
    (u"lo", u"Lao"),
    (u"lt", u"Lithuanian"),
    (u"lu", u"Luba-Katanga"),
    (u"lv", u"Latvian"),
    (u"gv", u"Manx"),
    (u"mk", u"Macedonian"),
    (u"mg", u"Malagasy"),
    (u"ms", u"Malay"),
    (u"ml", u"Malayalam"),
    (u"mt", u"Maltese"),
    (u"mr", u"Marathi"),
    (u"mh", u"Marshallese"),
    (u"mn", u"Mongolian"),
    (u"na", u"Nauru"),
    (u"nv", u"Navajo, Navaho"),
    (u"ne", u"Nepali"),
    (u"ng", u"Ndonga"),
    (u"nn", u"Norwegian Nynorsk"),
    (u"no", u"Norwegian"),
    (u"ii", u"Nuosu"),
    (u"nr", u"South Ndebele"),
    (u"oc", u"Occitan"),
    (u"oj", u"Ojibwe, Ojibwa"),
    (u"om", u"Oromo"),
    (u"os", u"Ossetian, Ossetic"),
    (u"pa", u"Panjabi, Punjabi"),
    (u"fa", u"Persian (Farsi)"),
    (u"pl", u"Polish"),
    (u"ps", u"Pashto, Pushto"),
    (u"pt", u"Portuguese"),
    (u"qu", u"Quechua"),
    (u"rm", u"Romansh"),
    (u"rn", u"Kirundi"),
    (u"ro", u"Romanian"),
    (u"ru", u"Russian"),
    (u"sa", u"Sanskrit"),
    (u"sc", u"Sardinian"),
    (u"sd", u"Sindhi"),
    (u"se", u"Northern Sami"),
    (u"sm", u"Samoan"),
    (u"sg", u"Sango"),
    (u"sr", u"Serbian"),
    (u"gd", u"Scottish Gaelic; Gaelic"),
    (u"sn", u"Shona"),
    (u"si", u"Sinhala, Sinhalese"),
    (u"sk", u"Slovak"),
    (u"sl", u"Slovene"),
    (u"so", u"Somali"),
    (u"st", u"Southern Sotho"),
    (u"es", u"Spanish; Castilian"),
    (u"su", u"Sundanese"),
    (u"sw", u"Swahili"),
    (u"ss", u"Swati"),
    (u"sv", u"Swedish"),
    (u"ta", u"Tamil"),
    (u"te", u"Telugu"),
    (u"tg", u"Tajik"),
    (u"th", u"Thai"),
    (u"ti", u"Tigrinya"),
    (u"bo", u"Tibetan Standard, Tibetan, Central"),
    (u"tk", u"Turkmen"),
    (u"tl", u"Tagalog"),
    (u"tn", u"Tswana"),
    (u"to", u"Tonga (Tonga Islands)"),
    (u"tr", u"Turkish"),
    (u"ts", u"Tsonga"),
    (u"tt", u"Tatar"),
    (u"tw", u"Twi"),
    (u"ty", u"Tahitian"),
    (u"ug", u"Uyghur, Uighur"),
    (u"uk", u"Ukrainian"),
    (u"ur", u"Urdu"),
    (u"uz", u"Uzbek"),
    (u"ve", u"Venda"),
    (u"vi", u"Vietnamese"),
    (u"wa", u"Walloon"),
    (u"cy", u"Welsh"),
    (u"wo", u"Wolof"),
    (u"fy", u"Western Frisian"),
    (u"xh", u"Xhosa"),
    (u"yi", u"Yiddish"),
    (u"yo", u"Yoruba"),
    (u"za", u"Zhuang, Chuang")
)

UOMS = (
    ("A1", "15 °C calorie"),
    ("M36", "30-day month"),
    ("A59", "8-part cloud cover"),
    ("84", "A unit of pressure defining the number of kilopounds force per square inch"),
    ("AL", "access line"),
    ("E50", "accounting unit"),
    ("ACR", "acre"),
    ("M67", "acre-foot (based on U.S. survey foot)"),
    ("E25", "active unit"),
    ("ACT", "activity"),
    ("26", "actual ton"),
    ("M37", "actual/360"),
    ("AH", "additional minute"),
    ("MD", "air dry metric ton"),
    ("E28", "air dry ton"),
    ("ASM", "alcoholic strength by mass"),
    ("ASU", "alcoholic strength by volume"),
    ("AP", "aluminium pound only"),
    ("AWG", "american wire gauge"),
    ("AMP", "ampere"),
    ("AMH", "ampere hour"),
    ("N95", "ampere minute"),
    ("A2", "ampere per centimetre"),
    ("H31", "ampere per kilogram"),
    ("AE", "ampere per metre"),
    ("A3", "ampere per millimetre"),
    ("N93", "ampere per pascal"),
    ("A4", "ampere per square centimetre"),
    ("A41", "ampere per square metre"),
    ("A6", "ampere per square metre kelvin squared"),
    ("A7", "ampere per square millimetre"),
    ("A8", "ampere second"),
    ("A5", "ampere square metre"),
    ("A10", "ampere square metre per joule second"),
    ("H32", "ampere squared second"),
    ("73", "ampere tum per centimetre"),
    ("AM", "ampoule"),
    ("A11", "angstrom"),
    ("AQ", "anti-hemophilic factor (AHF) unit"),
    ("ARE", "are"),
    ("AY", "assembly"),
    ("AS", "assortment"),
    ("A12", "astronomical unit"),
    ("H48", "attofarad"),
    ("A13", "attojoule"),
    ("AI", "average minute per call"),
    ("BG", "bag"),
    ("BL", "bale"),
    ("AA", "ball"),
    ("D92", "band"),
    ("BR", "bar [unit of packaging]"),
    ("BAR", "bar [unit of pressure]"),
    ("F92", "bar cubic metre per second"),
    ("F91", "bar litre per second"),
    ("J56", "bar per bar"),
    ("F81", "bar per kelvin"),
    ("NB", "barge"),
    ("A14", "barn"),
    ("A15", "barn per electronvolt"),
    ("A17", "barn per steradian"),
    ("A16", "barn per steradian electronvolt"),
    ("J57", "barrel (UK petroleum)"),
    ("J59", "barrel (UK petroleum) per day"),
    ("J60", "barrel (UK petroleum) per hour"),
    ("J58", "barrel (UK petroleum) per minute"),
    ("J61", "barrel (UK petroleum) per second"),
    ("J62", "barrel (US petroleum) per hour"),
    ("J63", "barrel (US petroleum) per second"),
    ("BLL", "barrel (US)"),
    ("B1", "barrel (US) per day"),
    ("5A", "barrel (US) per minute"),
    ("B4", "barrel, imperial"),
    ("BB", "base box"),
    ("BW", "base weight"),
    ("BK", "basket"),
    ("5B", "batch"),
    ("B9", "batt"),
    ("B3", "batting pound"),
    ("J38", "baud"),
    ("D79", "beam"),
    ("BPM", "beats per minute"),
    ("M19", "Beaufort"),
    ("BQL", "becquerel"),
    ("A19", "becquerel per cubic metre"),
    ("A18", "becquerel per kilogram"),
    ("M72", "bel"),
    ("P43", "bel per metre"),
    ("E2", "belt"),
    ("H82", "big point"),
    ("B5", "billet"),
    ("BIL", "billion (EUR)"),
    ("2W", "bin"),
    ("N96", "biot"),
    ("A99", "bit"),
    ("F01", "bit per cubic metre"),
    ("E88", "bit per metre"),
    ("B10", "bit per second"),
    ("E89", "bit per square metre"),
    ("H21", "blank"),
    ("D64", "block"),
    ("BD", "board"),
    ("BFT", "board foot"),
    ("4A", "bobbin"),
    ("BT", "bolt"),
    ("D63", "book"),
    ("BO", "bottle"),
    ("BX", "box"),
    ("BHP", "brake horse power"),
    ("N66", "British thermal unit (39 ºF) "),
    ("N67", "British thermal unit (59 ºF)"),
    ("N68", "British thermal unit (60 ºF) "),
    ("BTU", "British thermal unit (international table)"),
    ("J40", "British thermal unit (international table) foot per hour square foot degree Fahrenheit"),
    ("J41", "British thermal unit (international table) inch per hour square foot degree Fahrenheit"),
    ("J42", "British thermal unit (international table) inch per second square foot degree Fahrenheit"),
    ("N58", "British thermal unit (international table) per cubic foot "),
    ("N60", "British thermal unit (international table) per degree Fahrenheit"),
    ("N62", "British thermal unit (international table) per degree Rankine"),
    ("2I", "British thermal unit (international table) per hour"),
    ("N74", "British thermal unit (international table) per hour square foot degree Fahrenheit"),
    ("A23", "British thermal unit (international table) per hour square foot degree Rankine"),
    ("J44", "British thermal unit (international table) per minute"),
    ("AZ", "British thermal unit (international table) per pound"),
    ("J43", "British thermal unit (international table) per pound degree Fahrenheit"),
    ("A21", "British thermal unit (international table) per pound degree Rankine"),
    ("J45", "British thermal unit (international table) per second"),
    ("A22", "British thermal unit (international table) per second foot degree Rankine"),
    ("N76", "British thermal unit (international table) per second square foot degree Fahrenheit"),
    ("A20", "British thermal unit (international table) per second square foot degree Rankine"),
    ("P37", "British thermal unit (international table) per square foot"),
    ("N50", "British thermal unit (international table) per square foot hour"),
    ("N53", "British thermal unit (international table) per square foot second"),
    ("N55", "British thermal unit (international table) per square inch second"),
    ("J39", "British thermal unit (mean)"),
    ("J46", "British thermal unit (thermochemical) foot per hour square foot degree Fahrenheit"),
    ("J48", "British thermal unit (thermochemical) inch per hour square foot degree Fahrenheit"),
    ("J49", "British thermal unit (thermochemical) inch per second square foot degree Fahrenheit"),
    ("N59", "British thermal unit (thermochemical) per cubic foot"),
    ("N61", "British thermal unit (thermochemical) per degree Fahrenheit"),
    ("N63", "British thermal unit (thermochemical) per degree Rankine"),
    ("J47", "British thermal unit (thermochemical) per hour"),
    ("N75", "British thermal unit (thermochemical) per hour square foot degree Fahrenheit"),
    ("J51", "British thermal unit (thermochemical) per minute"),
    ("N73", "British thermal unit (thermochemical) per pound"),
    ("J50", "British thermal unit (thermochemical) per pound degree Fahrenheit"),
    ("N64", "British thermal unit (thermochemical) per pound degree Rankine"),
    ("J52", "British thermal unit (thermochemical) per second"),
    ("N77", "British thermal unit (thermochemical) per second square foot degree Fahrenheit"),
    ("P38", "British thermal unit (thermochemical) per square foot"),
    ("N51", "British thermal unit (thermochemical) per square foot hour"),
    ("N52", "British thermal unit (thermochemical) per square foot minute"),
    ("N54", "British thermal unit (thermochemical) per square foot second"),
    ("BH", "brush"),
    ("B0", "Btu per cubic foot"),
    ("BJ", "bucket"),
    ("VQ", "bulk"),
    ("48", "bulk car load"),
    ("AB", "bulk pack"),
    ("B6", "bun"),
    ("BE", "bundle"),
    ("B2", "bunk"),
    ("BUI", "bushel (UK)"),
    ("J64", "bushel (UK) per day"),
    ("J65", "bushel (UK) per hour"),
    ("J66", "bushel (UK) per minute"),
    ("J67", "bushel (UK) per second"),
    ("J68", "bushel (US dry) per day"),
    ("J69", "bushel (US dry) per hour"),
    ("J70", "bushel (US dry) per minute"),
    ("J71", "bushel (US dry) per second"),
    ("BUA", "bushel (US)"),
    ("AD", "byte"),
    ("P93", "byte per second"),
    ("1D", "caboose count"),
    ("1H", "caboose mile"),
    ("KA", "cake"),
    ("C0", "call"),
    ("R4", "calorie"),
    ("N69", "calorie (20 ºC) "),
    ("D70", "calorie (international table) "),
    ("D75", "calorie (international table) per gram"),
    ("J76", "calorie (international table) per gram degree Celsius"),
    ("D76", "calorie (international table) per gram kelvin"),
    ("D71", "calorie (international table) per second centimetre kelvin"),
    ("D72", "calorie (international table) per second square centimetre kelvin"),
    ("J75", "calorie (mean)"),
    ("D35", "calorie (thermochemical)"),
    ("J78", "calorie (thermochemical) per centimetre second degree Celsius"),
    ("B36", "calorie (thermochemical) per gram"),
    ("J79", "calorie (thermochemical) per gram degree Celsius"),
    ("D37", "calorie (thermochemical) per gram kelvin"),
    ("J81", "calorie (thermochemical) per minute"),
    ("J82", "calorie (thermochemical) per second"),
    ("D38", "calorie (thermochemical) per second centimetre kelvin"),
    ("D39", "calorie (thermochemical) per second square centimetre kelvin"),
    ("P39", "calorie (thermochemical) per square centimetre "),
    ("N56", "calorie (thermochemical) per square centimetre minute"),
    ("N57", "calorie (thermochemical) per square centimetre second"),
    ("92", "calorie per cubic centimetre"),
    ("93", "calorie per gram"),
    ("CA", "can"),
    ("CDL", "candela"),
    ("P32", "candela per square foot"),
    ("P28", "candela per square inch "),
    ("A24", "candela per square metre"),
    ("4B", "cap"),
    ("AV", "capsule"),
    ("NC", "car"),
    ("1B", "car count"),
    ("1A", "car mile"),
    ("CO", "carboy"),
    ("CG", "card"),
    ("C4", "carload"),
    ("CCT", "carrying capacity in metric ton"),
    ("C2", "carset"),
    ("CT", "carton"),
    ("CQ", "cartridge"),
    ("CS", "case"),
    ("Z3", "cask"),
    ("D66", "cassette"),
    ("31", "catch weight"),
    ("C6", "cell"),
    ("CNT", "cental (UK)"),
    ("CGM", "centigram"),
    ("CLT", "centilitre"),
    ("CMT", "centimetre"),
    ("J89", "centimetre of mercury"),
    ("N13", "centimetre of mercury (0 ºC)"),
    ("N14", "centimetre of water (4 ºC)"),
    ("G04", "centimetre per bar"),
    ("H49", "centimetre per hour"),
    ("F51", "centimetre per kelvin"),
    ("2M", "centimetre per second"),
    ("J85", "centimetre per second bar"),
    ("J84", "centimetre per second kelvin"),
    ("M39", "centimetre per second squared"),
    ("J72", "centinewton metre"),
    ("C7", "centipoise"),
    ("J74", "centipoise per bar"),
    ("J73", "centipoise per kelvin"),
    ("4C", "centistokes"),
    ("M49", "chain (based on U.S. survey foot)"),
    ("Z2", "chest"),
    ("A25", "cheval vapeur"),
    ("M47", "circular mil "),
    ("J83", "clo"),
    ("CL", "coil"),
    ("C9", "coil group"),
    ("II", "column inch"),
    ("CZ", "combo"),
    ("L95", "common year"),
    ("C1", "composite product pound (total weight)"),
    ("CJ", "cone"),
    ("Z6", "conference point"),
    ("CK", "connector"),
    ("CH", "container"),
    ("CTG", "content gram"),
    ("CTN", "content ton (metric)"),
    ("H78", "conventional centimetre of water"),
    ("N23", "conventional metre of water"),
    ("HN", "conventional millimetre of mercury"),
    ("HP", "conventional millimetre of water"),
    ("AJ", "cop"),
    ("WCD", "cord"),
    ("M68", "cord (128 ft3)"),
    ("C5", "cost"),
    ("COU", "coulomb"),
    ("A26", "coulomb metre"),
    ("A27", "coulomb metre squared per volt"),
    ("A28", "coulomb per cubic centimetre"),
    ("A29", "coulomb per cubic metre"),
    ("A30", "coulomb per cubic millimetre"),
    ("CKG", "coulomb per kilogram"),
    ("A31", "coulomb per kilogram second"),
    ("P10", "coulomb per metre"),
    ("A32", "coulomb per mole"),
    ("A33", "coulomb per square centimetre"),
    ("A34", "coulomb per square metre"),
    ("A35", "coulomb per square millimetre"),
    ("J53", "coulomb square metre per kilogram"),
    ("IT", "count per centimetre"),
    ("IC", "count per inch"),
    ("5K", "count per minute"),
    ("CV", "cover"),
    ("CR", "crate"),
    ("B17", "credit"),
    ("CMQ", "cubic centimetre"),
    ("G94", "cubic centimetre per bar"),
    ("J87", "cubic centimetre per cubic metre"),
    ("G47", "cubic centimetre per day"),
    ("G78", "cubic centimetre per day bar"),
    ("G61", "cubic centimetre per day kelvin"),
    ("G48", "cubic centimetre per hour"),
    ("G79", "cubic centimetre per hour bar"),
    ("G62", "cubic centimetre per hour kelvin"),
    ("G27", "cubic centimetre per kelvin"),
    ("G49", "cubic centimetre per minute"),
    ("G80", "cubic centimetre per minute bar"),
    ("G63", "cubic centimetre per minute kelvin"),
    ("A36", "cubic centimetre per mole"),
    ("2J", "cubic centimetre per second"),
    ("G81", "cubic centimetre per second bar"),
    ("G64", "cubic centimetre per second kelvin"),
    ("DMA", "cubic decametre"),
    ("DMQ", "cubic decimetre"),
    ("J91", "cubic decimetre per cubic metre"),
    ("J90", "cubic decimetre per day"),
    ("E92", "cubic decimetre per hour"),
    ("N28", "cubic decimetre per kilogram"),
    ("J92", "cubic decimetre per minute"),
    ("A37", "cubic decimetre per mole"),
    ("J93", "cubic decimetre per second"),
    ("FTQ", "cubic foot"),
    ("K22", "cubic foot per day"),
    ("K21", "cubic foot per degree Fahrenheit"),
    ("2K", "cubic foot per hour"),
    ("2L", "cubic foot per minute"),
    ("36", "cubic foot per minute per square foot"),
    ("N29", "cubic foot per pound"),
    ("K23", "cubic foot per psi"),
    ("E17", "cubic foot per second"),
    ("H19", "cubic hectometre"),
    ("INQ", "cubic inch"),
    ("G56", "cubic inch per hour"),
    ("G57", "cubic inch per minute"),
    ("N30", "cubic inch per pound"),
    ("G58", "cubic inch per second"),
    ("H20", "cubic kilometre"),
    ("MTQ", "cubic metre"),
    ("D90", "cubic metre (net)"),
    ("G96", "cubic metre per bar"),
    ("A38", "cubic metre per coulomb"),
    ("H60", "cubic metre per cubic metre"),
    ("G52", "cubic metre per day"),
    ("G86", "cubic metre per day bar"),
    ("G69", "cubic metre per day kelvin"),
    ("MQH", "cubic metre per hour"),
    ("G87", "cubic metre per hour bar"),
    ("G70", "cubic metre per hour kelvin"),
    ("G29", "cubic metre per kelvin"),
    ("A39", "cubic metre per kilogram"),
    ("G53", "cubic metre per minute"),
    ("G88", "cubic metre per minute bar"),
    ("G71", "cubic metre per minute kelvin"),
    ("A40", "cubic metre per mole"),
    ("M71", "cubic metre per pascal"),
    ("MQS", "cubic metre per second"),
    ("G89", "cubic metre per second bar"),
    ("G72", "cubic metre per second kelvin"),
    ("N45", "cubic metre per second pascal"),
    ("P87", "cubic metre per second square metre"),
    ("M69", "cubic mile (UK statute)"),
    ("MMQ", "cubic millimetre"),
    ("L21", "cubic millimetre per cubic metre"),
    ("YDQ", "cubic yard"),
    ("M12", "cubic yard per day"),
    ("M11", "cubic yard per degree Fahrenheit"),
    ("M13", "cubic yard per hour"),
    ("M15", "cubic yard per minute"),
    ("M14", "cubic yard per psi"),
    ("M16", "cubic yard per second"),
    ("CU", "cup"),
    ("G21", "cup [unit of volume]"),
    ("CUR", "curie"),
    ("A42", "curie per kilogram"),
    ("94", "curl unit"),
    ("B7", "cycle"),
    ("CY", "cylinder"),
    ("DQ", "data record"),
    ("DAY", "day"),
    ("A43", "deadweight tonnage"),
    ("DE", "deal"),
    ("DEC", "decade"),
    ("P41", "decade (logarithmic)"),
    ("DJ", "decagram"),
    ("A44", "decalitre"),
    ("A45", "decametre"),
    ("H75", "decapascal"),
    ("DAA", "decare"),
    ("2N", "decibel"),
    ("H51", "decibel per kilometre"),
    ("H52", "decibel per metre"),
    ("DG", "decigram"),
    ("DLT", "decilitre"),
    ("22", "decilitre per gram"),
    ("DMT", "decimetre"),
    ("DN", "decinewton metre"),
    ("A47", "decitex"),
    ("DTN", "decitonne"),
    ("DD", "degree [unit of angle]"),
    ("M45", "degree [unit of angle] per second squared"),
    ("J13", "degree API"),
    ("J17", "degree Balling"),
    ("J14", "degree Baume (origin scale)"),
    ("J15", "degree Baume (US heavy)"),
    ("J16", "degree Baume (US light)"),
    ("J18", "degree Brix"),
    ("CEL", "degree Celsius"),
    ("F60", "degree Celsius per bar"),
    ("H12", "degree Celsius per hour"),
    ("E98", "degree Celsius per kelvin"),
    ("H13", "degree Celsius per minute"),
    ("H14", "degree Celsius per second"),
    ("E10", "degree day"),
    ("FAH", "degree Fahrenheit"),
    ("N84", "degree Fahrenheit hour per British thermal unit (international table)"),
    ("N85", "degree Fahrenheit hour per British thermal unit (thermochemical)"),
    ("J22", "degree Fahrenheit hour square foot per British thermal unit (international table)"),
    ("N88", "degree Fahrenheit hour square foot per British thermal unit (international table) inch"),
    ("J19", "degree Fahrenheit hour square foot per British thermal unit (thermochemical)"),
    ("N89", "degree Fahrenheit hour square foot per British thermal unit (thermochemical) inch"),
    ("J21", "degree Fahrenheit per bar"),
    ("J23", "degree Fahrenheit per hour"),
    ("J20", "degree Fahrenheit per kelvin"),
    ("J24", "degree Fahrenheit per minute"),
    ("J25", "degree Fahrenheit per second"),
    ("N86", "degree Fahrenheit second per British thermal unit (international table)"),
    ("N87", "degree Fahrenheit second per British thermal unit (thermochemical)"),
    ("J27", "degree Oechsle"),
    ("H27", "degree per metre"),
    ("E96", "degree per second"),
    ("PLA", "degree Plato"),
    ("A48", "degree Rankine"),
    ("J28", "degree Rankine per hour"),
    ("J29", "degree Rankine per minute"),
    ("J30", "degree Rankine per second"),
    ("J31", "degree Twaddell"),
    ("A49", "denier"),
    ("M83", "denier "),
    ("B19", "digit"),
    ("Q25", "dioptre"),
    ("DY", "directory book"),
    ("DC", "disk (disc)"),
    ("DI", "dispenser"),
    ("DPT", "displacement tonnage"),
    ("DS", "display"),
    ("D67", "dollar per hour"),
    ("E27", "dose"),
    ("E39", "dots per inch"),
    ("DZN", "dozen"),
    ("DZP", "dozen pack"),
    ("DPR", "dozen pair"),
    ("DPC", "dozen piece"),
    ("DRL", "dozen roll"),
    ("DRM", "drachm (UK)"),
    ("D8", "draize score"),
    ("DRI", "dram (UK)"),
    ("DRA", "dram (US)"),
    ("DR", "drum"),
    ("BLD", "dry barrel (US)"),
    ("GLD", "dry gallon (US)"),
    ("PTD", "dry pint (US)"),
    ("DB", "dry pound"),
    ("QTD", "dry quart (US)"),
    ("DT", "dry ton"),
    ("DU", "dyne"),
    ("J94", "dyne centimetre"),
    ("M97", "dyne metre"),
    ("DX", "dyne per centimetre"),
    ("D9", "dyne per square centimetre"),
    ("A51", "dyne second per centimetre"),
    ("A52", "dyne second per centimetre to the fifth power"),
    ("A50", "dyne second per cubic centimetre"),
    ("EA", "each"),
    ("EC", "each per month"),
    ("P8", "eight pack"),
    ("EB", "electronic mail box"),
    ("A53", "electronvolt"),
    ("A54", "electronvolt per metre"),
    ("A55", "electronvolt square metre"),
    ("A56", "electronvolt square metre per kilogram"),
    ("EP", "eleven pack"),
    ("1E", "empty car"),
    ("EV", "envelope"),
    ("EQ", "equivalent gallon"),
    ("A57", "erg"),
    ("A58", "erg per centimetre"),
    ("A60", "erg per cubic centimetre"),
    ("A61", "erg per gram"),
    ("A62", "erg per gram second"),
    ("A63", "erg per second"),
    ("A64", "erg per second square centimetre"),
    ("A65", "erg per square centimetre second"),
    ("A66", "erg square centimetre"),
    ("A67", "erg square centimetre per gram"),
    ("Q11", "erlang"),
    ("E58", "exabit per second"),
    ("A68", "exajoule"),
    ("E67", "exbibit per cubic metre"),
    ("E65", "exbibit per metre"),
    ("E66", "exbibit per square metre"),
    ("E59", "exbibyte"),
    ("63", "failure rate in time"),
    ("FIT", "failures in time"),
    ("FAR", "farad"),
    ("H33", "farad per kilometre"),
    ("A69", "farad per metre"),
    ("AK", "fathom"),
    ("A70", "femtojoule"),
    ("Q32", "femtolitre"),
    ("A71", "femtometre"),
    ("FBM", "fibre metre"),
    ("F9", "fibre per cubic centimetre of air"),
    ("FB", "field"),
    ("98", "fifteen kg drum"),
    ("47", "fifty lb bag"),
    ("46", "fifty lb bulk bag"),
    ("18", "fiftyfive gallon (US) drum"),
    ("P5", "five pack"),
    ("44", "fivehundred kg bulk bag"),
    ("1I", "fixed rate"),
    ("FL", "flake ton"),
    ("OZI", "fluid ounce (UK)"),
    ("OZA", "fluid ounce (US)"),
    ("FOT", "foot"),
    ("M51", "foot (U.S. survey) "),
    ("K25", "foot of mercury"),
    ("K24", "foot of water"),
    ("N15", "foot of water (39.2 ºF)"),
    ("K13", "foot per degree Fahrenheit"),
    ("K14", "foot per hour"),
    ("FR", "foot per minute"),
    ("K17", "foot per psi"),
    ("FS", "foot per second"),
    ("K18", "foot per second degree Fahrenheit"),
    ("K19", "foot per second psi"),
    ("A73", "foot per second squared"),
    ("E33", "foot per thousand"),
    ("N46", "foot poundal"),
    ("85", "foot pound-force"),
    ("K15", "foot pound-force per hour"),
    ("K16", "foot pound-force per minute"),
    ("A74", "foot pound-force per second"),
    ("N27", "foot to the fourth power "),
    ("P27", "footcandle"),
    ("P29", "footlambert"),
    ("21", "forty foot container"),
    ("P4", "four pack"),
    ("N94", "franklin"),
    ("A75", "freight ton"),
    ("H79", "French gauge"),
    ("1G", "fuel usage gallon (US)"),
    ("M50", "furlong"),
    ("GZ", "gage system"),
    ("A76", "gal"),
    ("GLI", "gallon (UK)"),
    ("K26", "gallon (UK) per day"),
    ("K27", "gallon (UK) per hour"),
    ("K28", "gallon (UK) per second"),
    ("K30", "gallon (US liquid) per second"),
    ("GLL", "gallon (US)"),
    ("GB", "gallon (US) per day"),
    ("G50", "gallon (US) per hour"),
    ("GW", "gallon per thousand cubic foot"),
    ("5C", "gallon(US) per thousand"),
    ("P12", "gamma"),
    ("76", "gauss"),
    ("A77", "Gaussian CGS (Centimetre-Gram-Second system) unit of displacement"),
    ("A79", "Gaussian CGS (Centimetre-Gram-Second system) unit of electric charge"),
    ("A78", "Gaussian CGS (Centimetre-Gram-Second system) unit of electric current"),
    ("A80", "Gaussian CGS (Centimetre-Gram-Second system) unit of electric field strength"),
    ("A81", "Gaussian CGS (Centimetre-Gram-Second system) unit of electric polarization"),
    ("A82", "Gaussian CGS (Centimetre-Gram-Second system) unit of electric potential"),
    ("A83", "Gaussian CGS (Centimetre-Gram-Second system) unit of magnetization"),
    ("B30", "gibibit"),
    ("E71", "gibibit per cubic metre"),
    ("E69", "gibibit per metre"),
    ("E70", "gibibit per square metre"),
    ("E62", "gibibyte"),
    ("GBQ", "gigabecquerel"),
    ("B68", "gigabit"),
    ("B80", "gigabit per second"),
    ("E34", "gigabyte"),
    ("E68", "gigabyte per second"),
    ("E11", "gigacalorie"),
    ("A84", "gigacoulomb per cubic metre"),
    ("A85", "gigaelectronvolt"),
    ("A86", "gigahertz"),
    ("M18", "gigahertz metre"),
    ("GV", "gigajoule"),
    ("A87", "gigaohm"),
    ("A88", "gigaohm metre"),
    ("M26", "gigaohm per metre"),
    ("A89", "gigapascal"),
    ("A90", "gigawatt"),
    ("GWH", "gigawatt hour"),
    ("N97", "gilbert"),
    ("GII", "gill (UK)"),
    ("K32", "gill (UK) per day"),
    ("K33", "gill (UK) per hour"),
    ("K34", "gill (UK) per minute"),
    ("K35", "gill (UK) per second"),
    ("GIA", "gill (US)"),
    ("K36", "gill (US) per day"),
    ("K37", "gill (US) per hour"),
    ("K38", "gill (US) per minute"),
    ("K39", "gill (US) per second"),
    ("A91", "gon"),
    ("A91", "grade"),
    ("GRN", "grain"),
    ("K41", "grain per gallon (US)"),
    ("GRM", "gram"),
    ("M99", "gram centimetre per second"),
    ("H84", "gram millimetre"),
    ("GFI", "gram of fissile isotope"),
    ("GC", "gram per 100 gram"),
    ("F74", "gram per bar"),
    ("N41", "gram per centimetre second"),
    ("23", "gram per cubic centimetre"),
    ("G11", "gram per cubic centimetre bar"),
    ("G33", "gram per cubic centimetre kelvin"),
    ("F23", "gram per cubic decimetre"),
    ("G12", "gram per cubic decimetre bar"),
    ("G34", "gram per cubic decimetre kelvin"),
    ("A93", "gram per cubic metre"),
    ("G14", "gram per cubic metre bar"),
    ("G36", "gram per cubic metre kelvin"),
    ("F26", "gram per day"),
    ("F62", "gram per day bar"),
    ("F35", "gram per day kelvin"),
    ("F25", "gram per hertz"),
    ("F27", "gram per hour"),
    ("F63", "gram per hour bar"),
    ("F36", "gram per hour kelvin"),
    ("F14", "gram per kelvin"),
    ("GK", "gram per kilogram"),
    ("GL", "gram per litre"),
    ("G13", "gram per litre bar"),
    ("G35", "gram per litre kelvin"),
    ("GF", "gram per metre (gram per 100 centimetres)"),
    ("GJ", "gram per millilitre"),
    ("G15", "gram per millilitre bar"),
    ("G37", "gram per millilitre kelvin"),
    ("H76", "gram per millimetre"),
    ("F28", "gram per minute"),
    ("F64", "gram per minute bar"),
    ("F37", "gram per minute kelvin"),
    ("A94", "gram per mole"),
    ("F29", "gram per second"),
    ("F65", "gram per second bar"),
    ("F38", "gram per second kelvin"),
    ("25", "gram per square centimetre"),
    ("GM", "gram per square metre"),
    ("N24", "gram per square millimetre"),
    ("GDW", "gram, dry weight"),
    ("GIC", "gram, including container"),
    ("GIP", "gram, including inner packaging"),
    ("K31", "gram-force per square centimetre"),
    ("A95", "gray"),
    ("P61", "gray per hour"),
    ("P57", "gray per minute"),
    ("A96", "gray per second"),
    ("GGR", "great gross"),
    ("GRO", "gross"),
    ("GD", "gross barrel"),
    ("GN", "gross gallon"),
    ("E4", "gross kilogram"),
    ("GRT", "gross register ton"),
    ("GT", "gross ton"),
    ("GY", "gross yard"),
    ("10", "group"),
    ("X1", "Gunter's chain"),
    ("HD", "half dozen"),
    ("GH", "half gallon (US)"),
    ("HT", "half hour"),
    ("H2", "half litre"),
    ("H1", "half page – electronic"),
    ("PV", "half pint (US)"),
    ("SAN", "half year (6 months)"),
    ("Z11", "hanging container"),
    ("HA", "hank"),
    ("Q15", "hartley"),
    ("Q18", "hartley per second"),
    ("HEA", "head"),
    ("08", "heat lot"),
    ("HAR", "hectare"),
    ("HBA", "hectobar"),
    ("HGM", "hectogram"),
    ("HLT", "hectolitre"),
    ("HPA", "hectolitre of pure alcohol"),
    ("HMT", "hectometre"),
    ("A97", "hectopascal"),
    ("F94", "hectopascal cubic metre per second"),
    ("F93", "hectopascal litre per second"),
    ("E99", "hectopascal per bar"),
    ("F82", "hectopascal per kelvin"),
    ("P82", "hectopascal per metre"),
    ("P35", "Hefner-Kerze"),
    ("81", "henry"),
    ("H03", "henry per kiloohm"),
    ("A98", "henry per metre"),
    ("H04", "henry per ohm"),
    ("HTZ", "hertz"),
    ("H34", "hertz metre"),
    ("Z4", "hogshead"),
    ("30", "horse power day per air dry metric ton"),
    ("K42", "horsepower (boiler)"),
    ("K43", "horsepower (electric)"),
    ("HUR", "hour"),
    ("CEN", "hundred"),
    ("BP", "hundred board foot"),
    ("HBX", "hundred boxes"),
    ("HC", "hundred count"),
    ("HH", "hundred cubic foot"),
    ("FF", "hundred cubic metre"),
    ("16", "hundred fifteen kg drum"),
    ("HF", "hundred foot"),
    ("HL", "hundred foot (linear)"),
    ("HIU", "hundred international unit"),
    ("HK", "hundred kilogram"),
    ("HDW", "hundred kilogram, dry weight"),
    ("HKM", "hundred kilogram, net mass"),
    ("17", "hundred lb drum"),
    ("CLF", "hundred leave"),
    ("YL", "hundred linear yard"),
    ("JPS", "hundred metre"),
    ("CNP", "hundred pack"),
    ("CWA", "hundred pound (cwt) / hundred weight (US)"),
    ("HI", "hundred sheet"),
    ("HS", "hundred square foot"),
    ("HO", "hundred troy ounce"),
    ("CWI", "hundred weight (UK)"),
    ("HY", "hundred yard"),
    ("HE", "hundredth of a carat"),
    ("5J", "hydraulic horse power"),
    ("G3", "Imperial gallon per minute"),
    ("IM", "impression"),
    ("INH", "inch"),
    ("F79", "inch of mercury"),
    ("N16", "inch of mercury (32 ºF)"),
    ("N17", "inch of mercury (60 ºF)"),
    ("F78", "inch of water"),
    ("N18", "inch of water (39.2 ºF)"),
    ("N19", "inch of water (60 ºF)"),
    ("K45", "inch per degree Fahrenheit"),
    ("B82", "inch per linear foot"),
    ("M63", "inch per minute"),
    ("IL", "inch per minute"),
    ("K46", "inch per psi"),
    ("IU", "inch per second"),
    ("K47", "inch per second degree Fahrenheit"),
    ("K48", "inch per second psi"),
    ("IV", "inch per second squared"),
    ("H57", "inch per two pi radiant"),
    ("M61", "inch per year"),
    ("IA", "inch pound (pound inch)"),
    ("N47", "inch poundal"),
    ("D69", "inch to the fourth power"),
    ("IF", "inches of water"),
    ("IP", "insurance policy"),
    ("P36", "international candle "),
    ("ISD", "international sugar degree"),
    ("JR", "jar"),
    ("E51", "job"),
    ("JO", "joint"),
    ("JOU", "joule"),
    ("B8", "joule per cubic metre"),
    ("P17", "joule per day"),
    ("D95", "joule per gram"),
    ("P16", "joule per hour"),
    ("JE", "joule per kelvin"),
    ("J2", "joule per kilogram"),
    ("B11", "joule per kilogram kelvin"),
    ("B12", "joule per metre"),
    ("B14", "joule per metre to the fourth power"),
    ("P15", "joule per minute"),
    ("B15", "joule per mole"),
    ("B16", "joule per mole kelvin"),
    ("P14", "joule per second"),
    ("E43", "joule per square centimetre"),
    ("B13", "joule per square metre"),
    ("Q10", "joule per tesla"),
    ("B18", "joule second"),
    ("D73", "joule square metre"),
    ("B20", "joule square metre per kilogram"),
    ("JG", "jug"),
    ("JB", "jumbo"),
    ("KAT", "katal"),
    ("KG", "keg"),
    ("KEL", "kelvin"),
    ("H35", "kelvin metre per watt"),
    ("F61", "kelvin per bar"),
    ("F10", "kelvin per hour"),
    ("F02", "kelvin per kelvin"),
    ("F11", "kelvin per minute"),
    ("N79", "kelvin per pascal"),
    ("F12", "kelvin per second"),
    ("B21", "kelvin per watt"),
    ("C21", "kibibit"),
    ("E74", "kibibit per cubic metre"),
    ("E72", "kibibit per metre"),
    ("E73", "kibibit per square metre"),
    ("E64", "kibibyte"),
    ("B22", "kiloampere"),
    ("TAH", "kiloampere hour (thousand ampere hour)"),
    ("B24", "kiloampere per metre"),
    ("B23", "kiloampere per square metre"),
    ("KBA", "kilobar"),
    ("K50", "kilobaud"),
    ("2Q", "kilobecquerel"),
    ("B25", "kilobecquerel per kilogram"),
    ("C37", "kilobit"),
    ("C74", "kilobit per second"),
    ("2P", "kilobyte"),
    ("P94", "kilobyte per second"),
    ("E14", "kilocalorie (international table)"),
    ("N65", "kilocalorie (international table) per gram kelvin"),
    ("K52", "kilocalorie (international table) per hour metre degree Celsius"),
    ("K51", "kilocalorie (mean)"),
    ("K53", "kilocalorie (thermochemical)"),
    ("E15", "kilocalorie (thermochemical) per hour"),
    ("K54", "kilocalorie (thermochemical) per minute"),
    ("K55", "kilocalorie (thermochemical) per second"),
    ("P33", "kilocandela"),
    ("KB", "kilocharacter"),
    ("B26", "kilocoulomb"),
    ("B27", "kilocoulomb per cubic metre"),
    ("B28", "kilocoulomb per square metre"),
    ("2R", "kilocurie"),
    ("B29", "kiloelectronvolt"),
    ("N90", "kilofarad"),
    ("78", "kilogauss"),
    ("KGM", "kilogram"),
    ("M98", "kilogram centimetre per second"),
    ("KD", "kilogram decimal"),
    ("KDW", "kilogram drained net weight"),
    ("M94", "kilogram metre"),
    ("B31", "kilogram metre per second"),
    ("M77", "kilogram metre per second squared"),
    ("B32", "kilogram metre squared"),
    ("B33", "kilogram metre squared per second"),
    ("KNS", "kilogram named substance"),
    ("KCC", "kilogram of choline chloride"),
    ("KHY", "kilogram of hydrogen peroxide"),
    ("TMS", "kilogram of imported meat, less offal"),
    ("KMA", "kilogram of methylamine"),
    ("KNI", "kilogram of nitrogen"),
    ("KPP", "kilogram of phosphorus pentoxide (phosphoric anhydride)"),
    ("KPH", "kilogram of potassium hydroxide (caustic potash)"),
    ("KPO", "kilogram of potassium oxide"),
    ("KSH", "kilogram of sodium hydroxide (caustic soda)"),
    ("KSD", "kilogram of substance 90 % dry"),
    ("KWO", "kilogram of tungsten trioxide"),
    ("KUR", "kilogram of uranium"),
    ("32", "kilogram per air dry metric ton"),
    ("H53", "kilogram per bar"),
    ("G31", "kilogram per cubic centimetre"),
    ("G16", "kilogram per cubic centimetre bar"),
    ("G38", "kilogram per cubic centimetre kelvin"),
    ("B34", "kilogram per cubic decimetre"),
    ("H55", "kilogram per cubic decimetre bar"),
    ("H54", "kilogram per cubic decimetre kelvin"),
    ("KMQ", "kilogram per cubic metre"),
    ("G18", "kilogram per cubic metre bar"),
    ("G40", "kilogram per cubic metre kelvin"),
    ("M73", "kilogram per cubic metre pascal"),
    ("F30", "kilogram per day"),
    ("F66", "kilogram per day bar"),
    ("F39", "kilogram per day kelvin"),
    ("E93", "kilogram per hour"),
    ("F67", "kilogram per hour bar"),
    ("F40", "kilogram per hour kelvin"),
    ("F15", "kilogram per kelvin"),
    ("M29", "kilogram per kilogram"),
    ("3H", "kilogram per kilogram of product"),
    ("M31", "kilogram per kilometre"),
    ("F24", "kilogram per kilomol"),
    ("B35", "kilogram per litre"),
    ("G17", "kilogram per litre bar"),
    ("G39", "kilogram per litre kelvin"),
    ("KL", "kilogram per metre"),
    ("N39", "kilogram per metre day"),
    ("N40", "kilogram per metre hour"),
    ("N38", "kilogram per metre minute"),
    ("N37", "kilogram per metre second"),
    ("KW", "kilogram per millimetre"),
    ("KI", "kilogram per millimetre width"),
    ("F31", "kilogram per minute"),
    ("F68", "kilogram per minute bar"),
    ("F41", "kilogram per minute kelvin"),
    ("D74", "kilogram per mole"),
    ("M74", "kilogram per pascal"),
    ("3I", "kilogram per piece of product"),
    ("KGS", "kilogram per second"),
    ("F69", "kilogram per second bar"),
    ("F42", "kilogram per second kelvin"),
    ("M87", "kilogram per second pascal"),
    ("D5", "kilogram per square centimetre"),
    ("28", "kilogram per square metre"),
    ("Q28", "kilogram per square metre pascal second"),
    ("H56", "kilogram per square metre second"),
    ("F18", "kilogram square centimetre"),
    ("F19", "kilogram square millimetre"),
    ("MND", "kilogram, dry weight"),
    ("KIC", "kilogram, including container"),
    ("KIP", "kilogram, including inner packaging"),
    ("B37", "kilogram-force"),
    ("B38", "kilogram-force metre"),
    ("B39", "kilogram-force metre per second"),
    ("E44", "kilogram-force metre per square centimetre"),
    ("E42", "kilogram-force per square centimetre"),
    ("B40", "kilogram-force per square metre"),
    ("E41", "kilogram-force per square millimetre"),
    ("P24", "kilohenry"),
    ("KHZ", "kilohertz"),
    ("M17", "kilohertz metre"),
    ("KJO", "kilojoule"),
    ("P21", "kilojoule per day"),
    ("Q31", "kilojoule per gram"),
    ("P20", "kilojoule per hour"),
    ("B41", "kilojoule per kelvin"),
    ("B42", "kilojoule per kilogram"),
    ("B43", "kilojoule per kilogram kelvin"),
    ("P19", "kilojoule per minute"),
    ("B44", "kilojoule per mole"),
    ("P18", "kilojoule per second"),
    ("K6", "kilolitre"),
    ("4X", "kilolitre per hour"),
    ("KLX", "kilolux"),
    ("KTM", "kilometre"),
    ("KMT", "kilometre"),
    ("KMH", "kilometre per hour"),
    ("M62", "kilometre per second "),
    ("M38", "kilometre per second squared"),
    ("B45", "kilomole"),
    ("B46", "kilomole per cubic metre"),
    ("K60", "kilomole per cubic metre bar"),
    ("K59", "kilomole per cubic metre kelvin"),
    ("K58", "kilomole per hour"),
    ("P47", "kilomole per kilogram"),
    ("K61", "kilomole per minute"),
    ("E94", "kilomole per second"),
    ("B47", "kilonewton"),
    ("B48", "kilonewton metre"),
    ("N31", "kilonewton per metre"),
    ("KNM", "kilonewton per square metre"),
    ("B49", "kiloohm"),
    ("B50", "kiloohm metre"),
    ("KF", "kilopacket"),
    ("KPA", "kilopascal"),
    ("F03", "kilopascal per bar"),
    ("F83", "kilopascal per kelvin"),
    ("P81", "kilopascal per metre"),
    ("34", "kilopascal per millimetre"),
    ("33", "kilopascal square metre per gram"),
    ("B51", "kilopond"),
    ("M90", "kilopound per hour"),
    ("M75", "kilopound-force"),
    ("84", "kilopound-force per square inch"),
    ("KR", "kiloroentgen"),
    ("B52", "kilosecond"),
    ("KJ", "kilosegment"),
    ("B53", "kilosiemens"),
    ("B54", "kilosiemens per metre"),
    ("P13", "kilotesla"),
    ("KTN", "kilotonne"),
    ("KVR", "kilovar"),
    ("KVT", "kilovolt"),
    ("KVA", "kilovolt - ampere"),
    ("K5", "kilovolt ampere (reactive)"),
    ("C79", "kilovolt ampere hour"),
    ("K2", "kilovolt ampere reactive demand"),
    ("K3", "kilovolt ampere reactive hour"),
    ("B55", "kilovolt per metre"),
    ("KWT", "kilowatt"),
    ("K1", "kilowatt demand"),
    ("KWH", "kilowatt hour"),
    ("E46", "kilowatt hour per cubic metre"),
    ("D03", "kilowatt hour per hour"),
    ("E47", "kilowatt hour per kelvin"),
    ("N82", "kilowatt per metre degree Celsius"),
    ("N81", "kilowatt per metre kelvin"),
    ("N78", "kilowatt per square metre kelvin"),
    ("P11", "kiloweber"),
    ("B56", "kiloweber per metre"),
    ("N20", "kip per square inch"),
    ("KT", "kit"),
    ("KNT", "knot"),
    ("LH", "labour hour"),
    ("KLK", "lactic dry material percentage"),
    ("LAC", "lactose excess percentage"),
    ("P30", "lambert"),
    ("P40", "langley"),
    ("LJ", "large spray"),
    ("LR", "layer"),
    ("LEF", "leaf"),
    ("LN", "length"),
    ("05", "lift"),
    ("Z1", "lift van"),
    ("B57", "light year"),
    ("LC", "linear centimetre"),
    ("LF", "linear foot"),
    ("LI", "linear inch"),
    ("LM", "linear metre"),
    ("LY", "linear yard"),
    ("LX", "linear yard per pound"),
    ("LK", "link"),
    ("PTL", "liquid pint (US)"),
    ("LP", "liquid pound"),
    ("QTL", "liquid quart (US)"),
    ("LE", "lite"),
    ("LTR", "litre"),
    ("LPA", "litre of pure alcohol"),
    ("G95", "litre per bar"),
    ("LD", "litre per day"),
    ("G82", "litre per day bar"),
    ("G65", "litre per day kelvin"),
    ("E32", "litre per hour"),
    ("G83", "litre per hour bar"),
    ("G66", "litre per hour kelvin"),
    ("G28", "litre per kelvin"),
    ("H83", "litre per kilogram"),
    ("K62", "litre per litre"),
    ("L2", "litre per minute"),
    ("G84", "litre per minute bar"),
    ("G67", "litre per minute kelvin"),
    ("B58", "litre per mole"),
    ("G51", "litre per second"),
    ("G85", "litre per second bar"),
    ("G68", "litre per second kelvin"),
    ("NL", "load"),
    ("1C", "locomotive count"),
    ("1K", "locomotive mile"),
    ("LO", "lot  [unit of procurement]"),
    ("D04", "lot  [unit of weight]"),
    ("Z5", "lug"),
    ("LUM", "lumen"),
    ("B59", "lumen hour"),
    ("P25", "lumen per square foot "),
    ("B60", "lumen per square metre"),
    ("B61", "lumen per watt"),
    ("B62", "lumen second"),
    ("LS", "lump sum"),
    ("LUX", "lux"),
    ("B63", "lux hour"),
    ("B64", "lux second"),
    ("MA", "machine per unit"),
    ("M0", "magnetic tape"),
    ("3C", "manmonth"),
    ("D98", "mass pound"),
    ("MT", "mat"),
    ("B65", "maxwell"),
    ("Q3", "meal"),
    ("D11", "mebibit"),
    ("E77", "mebibit per cubic metre"),
    ("E75", "mebibit per metre"),
    ("E76", "mebibit per square metre"),
    ("E63", "mebibyte"),
    ("H38", "megaampere"),
    ("B66", "megaampere per square metre"),
    ("J54", "megabaud"),
    ("4N", "megabecquerel"),
    ("B67", "megabecquerel per kilogram"),
    ("D36", "megabit"),
    ("E20", "megabit per second"),
    ("4L", "megabyte"),
    ("P95", "megabyte per second"),
    ("D77", "megacoulomb"),
    ("B69", "megacoulomb per cubic metre"),
    ("B70", "megacoulomb per square metre"),
    ("B71", "megaelectronvolt"),
    ("2U", "megagram"),
    ("B72", "megagram per cubic metre"),
    ("2V", "megagram per hour"),
    ("MHZ", "megahertz"),
    ("H39", "megahertz kilometre"),
    ("M27", "megahertz metre"),
    ("3B", "megajoule"),
    ("JM", "megajoule per cubic metre"),
    ("JK", "megajoule per kilogram"),
    ("D78", "megajoule per second"),
    ("MAL", "megalitre"),
    ("MAM", "megametre"),
    ("B73", "meganewton"),
    ("B74", "meganewton metre"),
    ("B75", "megaohm"),
    ("H88", "megaohm kilometre"),
    ("B76", "megaohm metre"),
    ("H36", "megaohm per kilometre"),
    ("H37", "megaohm per metre"),
    ("MPA", "megapascal"),
    ("F98", "megapascal cubic metre per second"),
    ("F97", "megapascal litre per second"),
    ("F05", "megapascal per bar"),
    ("F85", "megapascal per kelvin"),
    ("E38", "megapixel"),
    ("B77", "megasiemens per metre"),
    ("MAR", "megavar"),
    ("B78", "megavolt"),
    ("MVA", "megavolt - ampere"),
    ("MAH", "megavolt ampere reactive hour"),
    ("B79", "megavolt per metre"),
    ("MAW", "megawatt"),
    ("MWH", "megawatt hour (1000 kW.h)"),
    ("E07", "megawatt hour per hour"),
    ("E08", "megawatt per hertz"),
    ("Q35", "megawatts per minute"),
    ("57", "mesh"),
    ("NF", "message"),
    ("NH", "message hour"),
    ("MTR", "metre"),
    ("D18", "metre kelvin"),
    ("G05", "metre per bar"),
    ("N83", "metre per degree Celcius metre"),
    ("M60", "metre per hour"),
    ("F52", "metre per kelvin"),
    ("2X", "metre per minute"),
    ("M53", "metre per pascal"),
    ("M55", "metre per radiant"),
    ("MTS", "metre per second"),
    ("L13", "metre per second bar"),
    ("L12", "metre per second kelvin"),
    ("M59", "metre per second pascal"),
    ("MSK", "metre per second squared"),
    ("H58", "metre per volt second"),
    ("B83", "metre to the fourth power"),
    ("CTM", "metric carat"),
    ("HJ", "metric horse power"),
    ("E5", "metric long ton"),
    ("TIC", "metric ton, including container"),
    ("TIP", "metric ton, including inner packaging"),
    ("LUB", "metric ton, lubricating oil"),
    ("NQ", "mho"),
    ("B84", "microampere"),
    ("B85", "microbar"),
    ("H08", "microbecquerel"),
    ("B86", "microcoulomb"),
    ("B87", "microcoulomb per cubic metre"),
    ("B88", "microcoulomb per square metre"),
    ("M5", "microcurie"),
    ("4O", "microfarad"),
    ("H28", "microfarad per kilometre"),
    ("B89", "microfarad per metre"),
    ("G7", "microfiche sheet"),
    ("MC", "microgram"),
    ("GQ", "microgram per cubic metre"),
    ("J35", "microgram per cubic metre bar"),
    ("J34", "microgram per cubic metre kelvin"),
    ("Q29", "microgram per hectogram"),
    ("J33", "microgram per kilogram"),
    ("H29", "microgram per litre"),
    ("P63", "microgray per hour"),
    ("P59", "microgray per minute"),
    ("P55", "microgray per second"),
    ("B90", "microhenry"),
    ("G98", "microhenry per kiloohm"),
    ("B91", "microhenry per metre"),
    ("G99", "microhenry per ohm"),
    ("M7", "micro-inch"),
    ("4G", "microlitre"),
    ("J36", "microlitre per litre"),
    ("4H", "micrometre (micron)"),
    ("F50", "micrometre per kelvin"),
    ("NR", "micromho"),
    ("FH", "micromole"),
    ("B92", "micronewton"),
    ("B93", "micronewton metre"),
    ("B94", "microohm"),
    ("B95", "microohm metre"),
    ("B96", "micropascal"),
    ("J32", "micropoise"),
    ("B97", "microradian"),
    ("B98", "microsecond"),
    ("B99", "microsiemens"),
    ("G42", "microsiemens per centimetre"),
    ("G43", "microsiemens per metre"),
    ("P72", "microsievert per hour"),
    ("P76", "microsievert per minute"),
    ("P67", "microsievert per second"),
    ("D81", "microtesla"),
    ("D82", "microvolt"),
    ("C3", "microvolt per metre"),
    ("D80", "microwatt"),
    ("D85", "microwatt per square metre"),
    ("M43", "mil"),
    ("M52", "mile (based on U.S. survey foot) "),
    ("SMI", "mile (statute mile)"),
    ("M42", "mile (statute mile) per second squared"),
    ("HM", "mile per hour (statute mile)"),
    ("M57", "mile per minute "),
    ("M58", "mile per second "),
    ("E12", "mille"),
    ("4K", "milliampere"),
    ("E09", "milliampere hour"),
    ("F59", "milliampere per bar"),
    ("F08", "milliampere per inch"),
    ("G59", "milliampere per litre minute"),
    ("F76", "milliampere per millimetre"),
    ("F57", "milliampere per pound-force per square inch"),
    ("MLD", "milliard"),
    ("MBR", "millibar"),
    ("F96", "millibar cubic metre per second"),
    ("F95", "millibar litre per second"),
    ("F04", "millibar per bar"),
    ("F84", "millibar per kelvin"),
    ("P34", "millicandela"),
    ("D86", "millicoulomb"),
    ("D88", "millicoulomb per cubic metre"),
    ("C8", "millicoulomb per kilogram"),
    ("D89", "millicoulomb per square metre"),
    ("MCU", "millicurie"),
    ("KO", "milliequivalence caustic potash per gram of product"),
    ("C10", "millifarad"),
    ("C11", "milligal"),
    ("MGM", "milligram"),
    ("F75", "milligram per bar"),
    ("GP", "milligram per cubic metre"),
    ("L18", "milligram per cubic metre bar"),
    ("L17", "milligram per cubic metre kelvin"),
    ("F32", "milligram per day"),
    ("F70", "milligram per day bar"),
    ("F43", "milligram per day kelvin"),
    ("H64", "milligram per gram"),
    ("4M", "milligram per hour"),
    ("F71", "milligram per hour bar"),
    ("F44", "milligram per hour kelvin"),
    ("F16", "milligram per kelvin"),
    ("NA", "milligram per kilogram"),
    ("M1", "milligram per litre"),
    ("C12", "milligram per metre"),
    ("F33", "milligram per minute"),
    ("F72", "milligram per minute bar"),
    ("F45", "milligram per minute kelvin"),
    ("F34", "milligram per second"),
    ("F73", "milligram per second bar"),
    ("F46", "milligram per second kelvin"),
    ("H63", "milligram per square centimetre"),
    ("MF", "milligram per square foot per side"),
    ("MK", "milligram per square inch"),
    ("GO", "milligram per square metre"),
    ("C13", "milligray"),
    ("P62", "milligray per hour"),
    ("P58", "milligray per minute"),
    ("P54", "milligray per second"),
    ("C14", "millihenry"),
    ("H05", "millihenry per kiloohm"),
    ("H06", "millihenry per ohm"),
    ("77", "milli-inch"),
    ("C15", "millijoule"),
    ("MLT", "millilitre"),
    ("WW", "millilitre of water"),
    ("G97", "millilitre per bar"),
    ("H65", "millilitre per cubic metre"),
    ("G54", "millilitre per day"),
    ("G90", "millilitre per day bar"),
    ("G73", "millilitre per day kelvin"),
    ("G55", "millilitre per hour"),
    ("G91", "millilitre per hour bar"),
    ("G74", "millilitre per hour kelvin"),
    ("G30", "millilitre per kelvin"),
    ("KX", "millilitre per kilogram"),
    ("L19", "millilitre per litre"),
    ("41", "millilitre per minute"),
    ("G92", "millilitre per minute bar"),
    ("G75", "millilitre per minute kelvin"),
    ("40", "millilitre per second"),
    ("G93", "millilitre per second bar"),
    ("G76", "millilitre per second kelvin"),
    ("M22", "millilitre per square centimetre minute"),
    ("35", "millilitre per square centimetre second"),
    ("MMT", "millimetre"),
    ("G06", "millimetre per bar"),
    ("E97", "millimetre per degree Celcius metre"),
    ("H67", "millimetre per hour"),
    ("F53", "millimetre per kelvin"),
    ("H81", "millimetre per minute"),
    ("C16", "millimetre per second"),
    ("M41", "millimetre per second squared"),
    ("H66", "millimetre per year"),
    ("C17", "millimetre squared per second"),
    ("G77", "millimetre to the fourth power"),
    ("C18", "millimole"),
    ("H68", "millimole per gram"),
    ("D87", "millimole per kilogram"),
    ("M33", "millimole per litre"),
    ("C20", "millinewton"),
    ("D83", "millinewton metre"),
    ("C22", "millinewton per metre"),
    ("E45", "milliohm"),
    ("C23", "milliohm metre"),
    ("F54", "milliohm per metre"),
    ("MIO", "million"),
    ("M9", "million Btu per 1000 cubic foot"),
    ("E16", "million Btu(IT) per hour"),
    ("BZ", "million BTUs"),
    ("FM", "million cubic foot"),
    ("HMQ", "million cubic metre"),
    ("MIU", "million international unit"),
    ("FD", "million particle per cubic foot"),
    ("UM", "million unit"),
    ("74", "millipascal"),
    ("P80", "millipascal per metre"),
    ("C24", "millipascal second"),
    ("L16", "millipascal second per bar"),
    ("L15", "millipascal second per kelvin"),
    ("C25", "milliradian"),
    ("2Y", "milliroentgen"),
    ("L31", "milliroentgen aequivalent men"),
    ("C26", "millisecond"),
    ("C27", "millisiemens"),
    ("H61", "millisiemens per centimetre"),
    ("C28", "millisievert"),
    ("P71", "millisievert per hour"),
    ("P75", "millisievert per minute"),
    ("P66", "millisievert per second"),
    ("C29", "millitesla"),
    ("2Z", "millivolt"),
    ("M35", "millivolt - ampere"),
    ("D49", "millivolt per kelvin"),
    ("C30", "millivolt per metre"),
    ("H62", "millivolt per minute"),
    ("C31", "milliwatt"),
    ("C32", "milliwatt per square metre"),
    ("C33", "milliweber"),
    ("D61", "minute [unit of angle]"),
    ("MIN", "minute [unit of time]"),
    ("5E", "MMSCF/day"),
    ("H77", "module width"),
    ("P52", "mol per cubic metre pascal"),
    ("P51", "mol per kilogram pascal"),
    ("C34", "mole"),
    ("C35", "mole per cubic decimetre"),
    ("C36", "mole per cubic metre"),
    ("L29", "mole per cubic metre bar"),
    ("L28", "mole per cubic metre kelvin"),
    ("P99", "mole per cubiv metre to the power sum of stoichiometric numbers"),
    ("L23", "mole per hour"),
    ("C19", "mole per kilogram"),
    ("L25", "mole per kilogram bar"),
    ("L24", "mole per kilogram kelvin"),
    ("C38", "mole per litre"),
    ("L27", "mole per litre bar"),
    ("L26", "mole per litre kelvin"),
    ("L30", "mole per minute"),
    ("E95", "mole per second"),
    ("M4", "monetary value"),
    ("MON", "month"),
    ("ZZ", "mutually defined"),
    ("C39", "nanoampere"),
    ("C40", "nanocoulomb"),
    ("C41", "nanofarad"),
    ("C42", "nanofarad per metre"),
    ("L32", "nanogram per kilogram"),
    ("P64", "nanogray per hour"),
    ("P60", "nanogray per minute"),
    ("P56", "nanogray per second"),
    ("C43", "nanohenry"),
    ("C44", "nanohenry per metre"),
    ("Q34", "nanolitre"),
    ("C45", "nanometre"),
    ("P22", "nanoohm"),
    ("C46", "nanoohm metre"),
    ("C47", "nanosecond"),
    ("G44", "nanosiemens per centimetre"),
    ("G45", "nanosiemens per metre"),
    ("P73", "nanosievert per hour"),
    ("P77", "nanosievert per minute"),
    ("P68", "nanosievert per second"),
    ("C48", "nanotesla"),
    ("C49", "nanowatt"),
    ("Q16", "natural unit of information"),
    ("Q19", "natural unit of information per second"),
    ("NMI", "nautical mile"),
    ("C50", "neper"),
    ("C51", "neper per second"),
    ("ND", "net barrel"),
    ("NG", "net gallon (us)"),
    ("NI", "net imperial gallon"),
    ("58", "net kilogram"),
    ("NE", "net litre"),
    ("NTT", "net register ton"),
    ("NT", "net ton"),
    ("Z8", "newspage agate line"),
    ("NEW", "newton"),
    ("F88", "newton centimetre"),
    ("NU", "newton metre"),
    ("F90", "newton metre per ampere"),
    ("F89", "newton metre per degree"),
    ("G19", "newton metre per kilogram"),
    ("Q27", "newton metre per metre"),
    ("M93", "newton metre per radian"),
    ("M34", "newton metre per square metre"),
    ("C53", "newton metre second"),
    ("C54", "newton metre squared per kilogram squared"),
    ("H41", "newton metre watt to the power minus 0,5"),
    ("H40", "newton per ampere"),
    ("M23", "newton per centimetre"),
    ("4P", "newton per metre"),
    ("F47", "newton per millimetre"),
    ("E01", "newton per square centimetre"),
    ("C55", "newton per square metre"),
    ("C56", "newton per square millimetre"),
    ("C57", "newton second"),
    ("C58", "newton second per metre"),
    ("N36", "newton second per square metre"),
    ("P49", "newton square metre per ampere"),
    ("NIL", "nil"),
    ("P9", "nine pack"),
    ("NAR", "number of articles"),
    ("NBB", "number of bobbins"),
    ("NCL", "number of cells"),
    ("NIU", "number of international units"),
    ("JWL", "number of jewels"),
    ("N2", "number of lines"),
    ("MV", "number of mults"),
    ("NMP", "number of packs"),
    ("NPR", "number of pairs"),
    ("NPL", "number of parcels"),
    ("NPT", "number of parts"),
    ("NRL", "number of rolls"),
    ("NJ", "number of screens"),
    ("D68", "number of words"),
    ("C59", "octave"),
    ("Q12", "octet"),
    ("Q13", "octet per second"),
    ("66", "oersted"),
    ("OHM", "ohm"),
    ("C60", "ohm centimetre"),
    ("P23", "ohm circular-mil per foot "),
    ("M24", "ohm kilometre"),
    ("C61", "ohm metre"),
    ("F56", "ohm per kilometre"),
    ("H26", "ohm per metre"),
    ("F55", "ohm per mile (statute mile)"),
    ("C62", "one"),
    ("Q26", "one per one"),
    ("OPM", "oscillations per minute"),
    ("ONZ", "ounce (avoirdupois)"),
    ("L39", "ounce (avoirdupois) per cubic inch"),
    ("G32", "ounce (avoirdupois) per cubic yard"),
    ("L33", "ounce (avoirdupois) per day"),
    ("L37", "ounce (avoirdupois) per gallon (UK)"),
    ("L38", "ounce (avoirdupois) per gallon (US)"),
    ("L34", "ounce (avoirdupois) per hour"),
    ("L35", "ounce (avoirdupois) per minute"),
    ("L36", "ounce (avoirdupois) per second"),
    ("N22", "ounce (avoirdupois) per square inch "),
    ("L40", "ounce (avoirdupois)-force"),
    ("L41", "ounce (avoirdupois)-force inch"),
    ("J95", "ounce (UK fluid) per day"),
    ("J96", "ounce (UK fluid) per hour"),
    ("J97", "ounce (UK fluid) per minute"),
    ("J98", "ounce (UK fluid) per second"),
    ("J99", "ounce (US fluid) per day"),
    ("K10", "ounce (US fluid) per hour"),
    ("K11", "ounce (US fluid) per minute"),
    ("K12", "ounce (US fluid) per second"),
    ("OZ", "ounce av"),
    ("4R", "ounce foot"),
    ("4Q", "ounce inch"),
    ("37", "ounce per square foot"),
    ("38", "ounce per square foot per 0,01inch"),
    ("ON", "ounce per square yard"),
    ("11", "outfit"),
    ("OT", "overtime hour"),
    ("ODE", "ozone depletion equivalent"),
    ("PK", "pack"),
    ("PA", "packet"),
    ("PD", "pad"),
    ("ZP", "page"),
    ("P0", "page - electronic"),
    ("QA", "page - facsimile"),
    ("QB", "page - hardcopy"),
    ("PQ", "page per inch"),
    ("PL", "pail"),
    ("PR", "pair"),
    ("PB", "pair inch"),
    ("PF", "pallet (lift)"),
    ("D97", "pallet/unit load"),
    ("OA", "panel"),
    ("C63", "parsec"),
    ("61", "part per billion (US)"),
    ("E40", "part per hundred thousand"),
    ("59", "part per million"),
    ("NX", "part per thousand"),
    ("PAL", "pascal"),
    ("G01", "pascal cubic metre per second"),
    ("F99", "pascal litre per second"),
    ("F07", "pascal per bar"),
    ("C64", "pascal per kelvin"),
    ("H42", "pascal per metre"),
    ("C65", "pascal second"),
    ("H07", "pascal second per bar"),
    ("C66", "pascal second per cubic metre"),
    ("F77", "pascal second per kelvin"),
    ("M32", "pascal second per litre"),
    ("C67", "pascal second per metre"),
    ("P79", "pascal square metre per kilogram"),
    ("P42", "pascal squared second"),
    ("P98", "pascal to the power sum of stoichiometric numbers"),
    ("E82", "pebibit per cubic metre"),
    ("E80", "pebibit per metre"),
    ("E81", "pebibit per square metre"),
    ("E60", "pebibyte"),
    ("G23", "peck"),
    ("L43", "peck (UK)"),
    ("L44", "peck (UK) per day"),
    ("L45", "peck (UK) per hour"),
    ("L46", "peck (UK) per minute"),
    ("L47", "peck (UK) per second"),
    ("L48", "peck (US dry) per day"),
    ("L49", "peck (US dry) per hour"),
    ("L50", "peck (US dry) per minute"),
    ("L51", "peck (US dry) per second"),
    ("PZ", "peck dry (UK)"),
    ("PY", "peck dry (US)"),
    ("N1", "pen calorie"),
    ("D23", "pen gram (protein)"),
    ("DWT", "pennyweight"),
    ("J12", "per mille per psi"),
    ("P1", "percent"),
    ("62", "percent per 1000 hour"),
    ("H96", "percent per bar"),
    ("H73", "percent per decakelvin"),
    ("H90", "percent per degree"),
    ("M25", "percent per degree Celsius"),
    ("H72", "percent per hectobar"),
    ("H93", "percent per hundred"),
    ("H98", "percent per inch"),
    ("H25", "percent per kelvin"),
    ("H99", "percent per metre"),
    ("J10", "percent per millimetre"),
    ("H71", "percent per month"),
    ("H89", "percent per ohm"),
    ("H92", "percent per one hundred thousand"),
    ("H91", "percent per ten thousand"),
    ("H94", "percent per thousand"),
    ("H95", "percent per volt"),
    ("VP", "percent volume"),
    ("60", "percent weight"),
    ("P91", "perm (0 ºC) "),
    ("P92", "perm (23 ºC) "),
    ("IE", "person"),
    ("E78", "petabit"),
    ("E79", "petabit per second"),
    ("E36", "petabyte"),
    ("C68", "petajoule"),
    ("N12", "Pferdestaerke"),
    ("M86", "pfund"),
    ("Q30", "pH (potential of Hydrogen)"),
    ("C69", "phon"),
    ("P26", "phot"),
    ("R1", "pica"),
    ("C70", "picoampere"),
    ("C71", "picocoulomb"),
    ("4T", "picofarad"),
    ("C72", "picofarad per metre"),
    ("C73", "picohenry"),
    ("Q33", "picolitre"),
    ("C52", "picometre"),
    ("H69", "picopascal per kilometre"),
    ("H70", "picosecond"),
    ("N92", "picosiemens"),
    ("L42", "picosiemens per metre"),
    ("N99", "picovolt"),
    ("C75", "picowatt"),
    ("C76", "picowatt per square metre"),
    ("H87", "piece"),
    ("E19", "ping"),
    ("PTI", "pint (UK)"),
    ("L53", "pint (UK) per day"),
    ("L54", "pint (UK) per hour"),
    ("L55", "pint (UK) per minute"),
    ("L56", "pint (UK) per second"),
    ("L61", "pint (US dry)"),
    ("L57", "pint (US liquid) per day"),
    ("L58", "pint (US liquid) per hour"),
    ("L59", "pint (US liquid) per minute"),
    ("L60", "pint (US liquid) per second"),
    ("PT", "pint (US)"),
    ("JNT", "pipeline joint"),
    ("PI", "pitch"),
    ("E37", "pixel"),
    ("PG", "plate"),
    ("89", "poise"),
    ("F06", "poise per bar"),
    ("F86", "poise per kelvin"),
    ("N35", "poise per pascal"),
    ("M78", "pond"),
    ("PTN", "portion"),
    ("LBR", "pound"),
    ("K69", "pound (avoirdupois) per cubic foot degree Fahrenheit"),
    ("K70", "pound (avoirdupois) per cubic foot psi"),
    ("K75", "pound (avoirdupois) per cubic inch degree Fahrenheit"),
    ("K76", "pound (avoirdupois) per cubic inch psi"),
    ("K66", "pound (avoirdupois) per day"),
    ("K64", "pound (avoirdupois) per degree Fahrenheit"),
    ("K71", "pound (avoirdupois) per gallon (UK)"),
    ("K73", "pound (avoirdupois) per hour degree Fahrenheit"),
    ("K74", "pound (avoirdupois) per hour psi"),
    ("K78", "pound (avoirdupois) per minute"),
    ("K79", "pound (avoirdupois) per minute degree Fahrenheit"),
    ("K80", "pound (avoirdupois) per minute psi"),
    ("K77", "pound (avoirdupois) per psi"),
    ("K81", "pound (avoirdupois) per second"),
    ("K82", "pound (avoirdupois) per second degree Fahrenheit"),
    ("K83", "pound (avoirdupois) per second psi"),
    ("K65", "pound (avoirdupois) square foot"),
    ("PE", "pound equivalent"),
    ("N10", "pound foot per second"),
    ("C77", "pound gage"),
    ("D96", "pound gross"),
    ("N11", "pound inch per second"),
    ("F20", "pound inch squared"),
    ("P44", "pound mole"),
    ("P46", "pound mole per minute"),
    ("P48", "pound mole per pound"),
    ("P45", "pound mole per second"),
    ("PN", "pound net"),
    ("NY", "pound per air dry metric ton"),
    ("87", "pound per cubic foot"),
    ("LA", "pound per cubic inch"),
    ("K84", "pound per cubic yard"),
    ("P2", "pound per foot"),
    ("N44", "pound per foot day"),
    ("K67", "pound per foot hour"),
    ("N43", "pound per foot minute"),
    ("K68", "pound per foot second"),
    ("GE", "pound per gallon (US)"),
    ("4U", "pound per hour"),
    ("PO", "pound per inch of length"),
    ("PW", "pound per inch of width"),
    ("3G", "pound per piece of product"),
    ("M91", "pound per pound"),
    ("3E", "pound per pound of product"),
    ("RP", "pound per ream"),
    ("FP", "pound per square foot"),
    ("80", "pound per square inch absolute"),
    ("64", "pound per square inch, gauge"),
    ("N25", "pound per square yard"),
    ("5F", "pound per thousand"),
    ("29", "pound per thousand square foot"),
    ("M84", "pound per yard "),
    ("PM", "pound percentage"),
    ("M76", "poundal"),
    ("M95", "poundal foot"),
    ("M96", "poundal inch"),
    ("N32", "poundal per inch"),
    ("N21", "poundal per square foot "),
    ("N26", "poundal per square inch"),
    ("N34", "poundal second per square foot "),
    ("N42", "poundal second per square inch"),
    ("C78", "pound-force"),
    ("M92", "pound-force foot"),
    ("F22", "pound-force foot per ampere"),
    ("P89", "pound-force foot per inch"),
    ("G20", "pound-force foot per pound"),
    ("F21", "pound-force inch"),
    ("P90", "pound-force inch per inch "),
    ("F17", "pound-force per foot"),
    ("F48", "pound-force per inch"),
    ("K85", "pound-force per square foot"),
    ("PS", "pound-force per square inch"),
    ("K86", "pound-force per square inch degree Fahrenheit"),
    ("N33", "pound-force per yard"),
    ("K91", "pound-force second per square foot"),
    ("K92", "pound-force second per square inch"),
    ("AW", "powder filled vial"),
    ("N3", "print point"),
    ("PGL", "proof gallon"),
    ("PFL", "proof litre"),
    ("K87", "psi cubic inch per second"),
    ("K89", "psi cubic metre per second"),
    ("K90", "psi cubic yard per second"),
    ("K88", "psi litre per second"),
    ("P86", "psi per inch"),
    ("L52", "psi per psi"),
    ("5G", "pump"),
    ("N70", "quad (1015 BtuIT)"),
    ("K94", "quart (UK liquid) per day"),
    ("K95", "quart (UK liquid) per hour"),
    ("K96", "quart (UK liquid) per minute"),
    ("K97", "quart (UK liquid) per second"),
    ("QTI", "quart (UK)"),
    ("L62", "quart (US dry)"),
    ("K98", "quart (US liquid) per day"),
    ("K99", "quart (US liquid) per hour"),
    ("L10", "quart (US liquid) per minute"),
    ("L11", "quart (US liquid) per second"),
    ("QT", "quart (US)"),
    ("QAN", "quarter (of a year)"),
    ("QTR", "quarter (UK)"),
    ("QD", "quarter dozen"),
    ("QH", "quarter hour"),
    ("QK", "quarter kilogram"),
    ("1X", "quarter mile"),
    ("QR", "quire"),
    ("RA", "rack"),
    ("H80", "rack unit"),
    ("C80", "rad"),
    ("C81", "radian"),
    ("C84", "radian per metre"),
    ("2A", "radian per second"),
    ("2B", "radian per second squared"),
    ("C83", "radian square metre per kilogram"),
    ("C82", "radian square metre per mole"),
    ("A9", "rate"),
    ("13", "ration"),
    ("RM", "ream"),
    ("RN", "ream metric measure"),
    ("C85", "reciprocal angstrom"),
    ("F58", "reciprocal bar"),
    ("E90", "reciprocal centimetre"),
    ("H50", "reciprocal cubic centimetre"),
    ("K20", "reciprocal cubic foot"),
    ("K49", "reciprocal cubic inch"),
    ("C86", "reciprocal cubic metre"),
    ("C87", "reciprocal cubic metre per second"),
    ("L20", "reciprocal cubic millimetre"),
    ("M10", "reciprocal cubic yard"),
    ("E91", "reciprocal day"),
    ("J26", "reciprocal degree Fahrenheit"),
    ("C88", "reciprocal electron volt per cubic metre"),
    ("C89", "reciprocal henry"),
    ("H10", "reciprocal hour"),
    ("Q24", "reciprocal inch"),
    ("N91", "reciprocal joule"),
    ("C90", "reciprocal joule per cubic metre"),
    ("C91", "reciprocal kelvin or kelvin to the power minus one"),
    ("M21", "reciprocal kilovolt - ampere reciprocal hour"),
    ("K63", "reciprocal litre"),
    ("M20", "reciprocal megakelvin or megakelvin to the power minus one"),
    ("C92", "reciprocal metre"),
    ("B81", "reciprocal metre squared reciprocal second"),
    ("C94", "reciprocal minute"),
    ("C95", "reciprocal mole"),
    ("H11", "reciprocal month"),
    ("C96", "reciprocal pascal or pascal to the power minus one"),
    ("K93", "reciprocal psi"),
    ("P97", "reciprocal radian"),
    ("C97", "reciprocal second"),
    ("C98", "reciprocal second per cubic metre"),
    ("C99", "reciprocal second per metre squared"),
    ("D1", "reciprocal second per steradian"),
    ("D2", "reciprocal second per steradian metre squared"),
    ("P78", "reciprocal square inch"),
    ("C93", "reciprocal square metre"),
    ("P96", "reciprocal volt"),
    ("M30", "reciprocal volt - ampere reciprocal second"),
    ("H85", "reciprocal week"),
    ("H09", "reciprocal year"),
    ("RL", "reel"),
    ("D91", "rem"),
    ("P69", "rem per second"),
    ("RS", "reset"),
    ("RT", "revenue ton mile"),
    ("M44", "revolution"),
    ("M46", "revolution per minute "),
    ("RPM", "revolutions per minute"),
    ("RPS", "revolutions per second"),
    ("P88", "rhe"),
    ("RG", "ring"),
    ("RD", "rod"),
    ("F49", "rod [unit of distance]"),
    ("2C", "roentgen"),
    ("D6", "roentgen per second"),
    ("RO", "roll"),
    ("RK", "roll metric measure"),
    ("ROM", "room"),
    ("D65", "round"),
    ("RU", "run"),
    ("E52", "run foot"),
    ("RH", "running or operating hour"),
    ("SA", "sack"),
    ("D7", "sandwich"),
    ("90", "Saybold universal second"),
    ("SCO", "score"),
    ("SCR", "scruple"),
    ("D62", "second [unit of angle]"),
    ("SEC", "second [unit of time]"),
    ("D93", "second per cubic metre"),
    ("D94", "second per cubic metre radian"),
    ("Q20", "second per kilogramm"),
    ("Q22", "second per radian cubic metre"),
    ("SE", "section"),
    ("SG", "segment"),
    ("5P", "seismic level"),
    ("5Q", "seismic line"),
    ("E48", "service unit"),
    ("S6", "session"),
    ("SET", "set"),
    ("P7", "seven pack"),
    ("M56", "shake"),
    ("Q14", "shannon"),
    ("Q17", "shannon per second"),
    ("E21", "shares"),
    ("ST", "sheet"),
    ("SS", "sheet metric measure"),
    ("SP", "shelf package"),
    ("SX", "shipment"),
    ("SHT", "shipping ton"),
    ("SST", "short standard (7200 matches)"),
    ("14", "shot"),
    ("L96", "sidereal year"),
    ("SIE", "siemens"),
    ("H43", "siemens per centimetre"),
    ("D10", "siemens per metre"),
    ("D12", "siemens square metre per mole"),
    ("D13", "sievert"),
    ("P70", "sievert per hour"),
    ("P74", "sievert per minute"),
    ("P65", "sievert per second"),
    ("56", "sitas"),
    ("P6", "six pack"),
    ("S5", "sixty fourths of an inch"),
    ("SW", "skein"),
    ("SV", "skid"),
    ("D99", "sleeve"),
    ("SL", "slipsheet"),
    ("F13", "slug"),
    ("L65", "slug per cubic foot"),
    ("L63", "slug per day"),
    ("L64", "slug per foot second"),
    ("L66", "slug per hour"),
    ("L67", "slug per minute"),
    ("L68", "slug per second"),
    ("06", "small spray"),
    ("SD", "solid pound"),
    ("D15", "sone"),
    ("SK", "split tank truck"),
    ("SO", "spool"),
    ("SQ", "square"),
    ("CMK", "square centimetre"),
    ("D16", "square centimetre per erg"),
    ("H15", "square centimetre per gram"),
    ("M81", "square centimetre per second"),
    ("D17", "square centimetre per steradian erg"),
    ("H16", "square decametre"),
    ("DMK", "square decimetre"),
    ("FTK", "square foot"),
    ("M79", "square foot per hour "),
    ("S3", "square foot per second"),
    ("H18", "square hectometre"),
    ("INK", "square inch"),
    ("G08", "square inch per second"),
    ("KMK", "square kilometre"),
    ("MTK", "square metre"),
    ("L14", "square metre hour degree Celsius per kilocalorie (international table)"),
    ("D19", "square metre kelvin per watt"),
    ("Q36", "square metre per cubic metre"),
    ("D20", "square metre per joule"),
    ("D21", "square metre per kilogram"),
    ("E31", "square metre per litre"),
    ("D22", "square metre per mole"),
    ("H59", "square metre per newton"),
    ("S4", "square metre per second"),
    ("G41", "square metre per second bar"),
    ("G09", "square metre per second kelvin"),
    ("M82", "square metre per second pascal"),
    ("D24", "square metre per steradian"),
    ("D25", "square metre per steradian joule"),
    ("D26", "square metre per volt second"),
    ("H30", "square micrometre (square micron)"),
    ("M48", "square mile (based on U.S. survey foot) "),
    ("MIK", "square mile (statute mile)"),
    ("MMK", "square millimetre"),
    ("SN", "square rod"),
    ("YDK", "square yard"),
    ("SQR", "square, roofing"),
    ("5H", "stage"),
    ("WSD", "standard"),
    ("K40", "standard acceleration of free fall"),
    ("S8", "standard advertising unit"),
    ("ATM", "standard atmosphere"),
    ("P83", "standard atmosphere per metre"),
    ("5I", "standard cubic foot"),
    ("DMO", "standard kilolitre"),
    ("STL", "standard litre"),
    ("D27", "steradian"),
    ("G26", "stere"),
    ("STC", "stick"),
    ("STK", "stick, cigarette"),
    ("15", "stick, military"),
    ("P31", "stilb"),
    ("91", "stokes"),
    ("G46", "stokes per bar"),
    ("G10", "stokes per kelvin"),
    ("M80", "stokes per pascal"),
    ("STI", "stone (UK)"),
    ("S7", "storage unit"),
    ("E30", "strand"),
    ("STW", "straw"),
    ("SR", "strip"),
    ("43", "super bulk bag"),
    ("AR", "suppository"),
    ("D28", "syphon"),
    ("SYR", "syringe"),
    ("G24", "tablespoon (US)"),
    ("U2", "tablet"),
    ("19", "tank truck"),
    ("TY", "tank, cylindrical"),
    ("TK", "tank, rectangular"),
    ("G25", "teaspoon (US)"),
    ("E86", "tebibit per cubic metre"),
    ("E85", "tebibit per metre"),
    ("E87", "tebibit per square metre"),
    ("E61", "tebibyte"),
    ("ATT", "technical atmosphere"),
    ("P84", "technical atmosphere per metre"),
    ("TPI", "teeth per inch"),
    ("T0", "telecommunication line in service"),
    ("UB", "telecommunication line in service average"),
    ("UC", "telecommunication port"),
    ("DAD", "ten day"),
    ("97", "ten kg drum"),
    ("TP", "ten pack"),
    ("TPR", "ten pair"),
    ("TST", "ten set"),
    ("TR", "ten square foot"),
    ("TF", "ten square yard"),
    ("96", "ten thousand gallon (US) tankcar"),
    ("TTS", "ten thousand sticks"),
    ("UH", "ten thousand yard"),
    ("YT", "ten yard"),
    ("TA", "tenth cubic foot"),
    ("UE", "tenth hour"),
    ("UD", "tenth minute"),
    ("E83", "terabit"),
    ("E84", "terabit per second"),
    ("E35", "terabyte"),
    ("D29", "terahertz"),
    ("D30", "terajoule"),
    ("H44", "teraohm"),
    ("D31", "terawatt"),
    ("D32", "terawatt hour"),
    ("D33", "tesla"),
    ("E53", "test"),
    ("69", "test specific scale"),
    ("E22", "TEU"),
    ("D34", "tex"),
    ("53", "theoretical kilogram"),
    ("24", "theoretical pound"),
    ("27", "theoretical ton"),
    ("54", "theoretical tonne"),
    ("TD", "therm"),
    ("N71", "therm (EC)"),
    ("N72", "therm (U.S.)"),
    ("MIL", "thousand"),
    ("T4", "thousand bag"),
    ("MBF", "thousand board foot"),
    ("T5", "thousand casing"),
    ("FC", "thousand cubic foot"),
    ("F1", "thousand cubic foot per day"),
    ("R9", "thousand cubic metre"),
    ("TQD", "thousand cubic metre per day"),
    ("TQ", "thousand foot"),
    ("TL", "thousand foot (linear)"),
    ("T6", "thousand gallon (US)"),
    ("T7", "thousand impression"),
    ("TV", "thousand kilogram"),
    ("T8", "thousand linear inch"),
    ("TT", "thousand linear metre"),
    ("D14", "thousand linear yard"),
    ("D40", "thousand litre"),
    ("MQ", "thousand metre"),
    ("T3", "thousand piece"),
    ("T1", "thousand pound gross"),
    ("KS", "thousand pound per square inch"),
    ("TW", "thousand sheet"),
    ("TJ", "thousand square centimetre"),
    ("TS", "thousand square foot"),
    ("TI", "thousand square inch"),
    ("MBE", "thousand standard brick equivalent"),
    ("P3", "three pack"),
    ("45", "threehundred kg bulk bag"),
    ("TN", "tin"),
    ("L92", "ton (UK long) per cubic yard"),
    ("L84", "ton (UK shipping)"),
    ("LTN", "ton (UK) or long ton (US)"),
    ("L86", "ton (US shipping)"),
    ("L93", "ton (US short) per cubic yard"),
    ("STN", "ton (US) or short ton (UK/US)"),
    ("4W", "ton (US) per hour"),
    ("L85", "ton long per day"),
    ("1J", "ton mile"),
    ("TSH", "ton of steam per hour"),
    ("L88", "ton short per day"),
    ("L87", "ton short per degree Fahrenheit"),
    ("L89", "ton short per hour degree Fahrenheit"),
    ("L90", "ton short per hour psi"),
    ("L91", "ton short per psi"),
    ("M85", "ton, assay"),
    ("M70", "ton, register "),
    ("L94", "ton-force (US short)"),
    ("TNE", "tonne (metric ton)"),
    ("TKM", "tonne kilometre"),
    ("TSD", "tonne of substance 90 % dry"),
    ("L70", "tonne per bar"),
    ("D41", "tonne per cubic metre"),
    ("L77", "tonne per cubic metre bar"),
    ("L76", "tonne per cubic metre kelvin"),
    ("L71", "tonne per day"),
    ("L73", "tonne per day bar"),
    ("L72", "tonne per day kelvin"),
    ("E18", "tonne per hour"),
    ("L75", "tonne per hour bar"),
    ("L74", "tonne per hour kelvin"),
    ("L69", "tonne per kelvin"),
    ("L78", "tonne per minute"),
    ("L80", "tonne per minute bar"),
    ("L79", "tonne per minute kelvin"),
    ("M88", "tonne per month"),
    ("L81", "tonne per second"),
    ("L83", "tonne per second bar"),
    ("L82", "tonne per second kelvin"),
    ("M89", "tonne per year"),
    ("UA", "torr"),
    ("P85", "torr per metre"),
    ("TAN", "total acid number"),
    ("1L", "total car count"),
    ("1M", "total car mile"),
    ("TE", "tote"),
    ("FE", "track foot"),
    ("E3", "trailer"),
    ("NN", "train"),
    ("1F", "train mile"),
    ("FG", "transdermal patch"),
    ("PU", "tray / tray pack"),
    ("U1", "treatment"),
    ("TRL", "trillion (EUR)"),
    ("E54", "trip"),
    ("D42", "tropical year"),
    ("APZ", "troy ounce or apothecary ounce"),
    ("LBT", "troy pound (US)"),
    ("TC", "truckload"),
    ("TU", "tube"),
    ("20", "twenty foot container"),
    ("4E", "twenty pack"),
    ("95", "twenty thousand gallon (US) tankcar"),
    ("OP", "two pack"),
    ("W4", "two week"),
    ("E23", "tyre"),
    ("D43", "unified atomic mass unit"),
    ("P53", "unit pole "),
    ("G2", "US gallon per minute"),
    ("UF", "usage per telecommunication line average"),
    ("E55", "use"),
    ("D44", "var"),
    ("NV", "vehicle"),
    ("VI", "vial"),
    ("VS", "visit"),
    ("VLT", "volt"),
    ("D46", "volt - ampere"),
    ("VA", "volt - ampere per kilogram"),
    ("2G", "volt AC"),
    ("71", "volt ampere per pound"),
    ("2H", "volt DC"),
    ("G60", "volt per bar"),
    ("D47", "volt per centimetre"),
    ("H23", "volt per inch"),
    ("D48", "volt per kelvin"),
    ("F87", "volt per litre minute"),
    ("D50", "volt per metre"),
    ("H24", "volt per microsecond"),
    ("D51", "volt per millimetre"),
    ("N98", "volt per pascal"),
    ("H46", "volt per second"),
    ("H45", "volt second per metre"),
    ("H22", "volt square inch per pound-force"),
    ("D45", "volt squared per kelvin squared"),
    ("F80", "water horse power"),
    ("WTT", "watt"),
    ("WHR", "watt hour"),
    ("H47", "watt per cubic metre"),
    ("D52", "watt per kelvin"),
    ("WA", "watt per kilogram"),
    ("H74", "watt per metre"),
    ("N80", "watt per metre degree Celsius"),
    ("D53", "watt per metre kelvin"),
    ("72", "watt per pound"),
    ("N48", "watt per square centimetre "),
    ("N49", "watt per square inch "),
    ("D54", "watt per square metre"),
    ("D55", "watt per square metre kelvin"),
    ("D56", "watt per square metre kelvin to the fourth power"),
    ("D57", "watt per steradian"),
    ("D58", "watt per steradian square metre"),
    ("J55", "watt second"),
    ("Q21", "watt square metre"),
    ("WEB", "weber"),
    ("P50", "weber metre"),
    ("D59", "weber per metre"),
    ("D60", "weber per millimetre"),
    ("Q23", "weber to the power minus one"),
    ("WEE", "week"),
    ("WI", "weight per square inch"),
    ("E56", "well"),
    ("W2", "wet kilo"),
    ("WB", "wet pound"),
    ("WE", "wet ton"),
    ("WH", "wheel"),
    ("WG", "wine gallon"),
    ("E49", "working day"),
    ("WM", "working month"),
    ("WR", "wrap"),
    ("YRD", "yard"),
    ("L98", "yard per degree Fahrenheit"),
    ("M66", "yard per hour"),
    ("M65", "yard per minute"),
    ("L99", "yard per psi"),
    ("M64", "yard per second"),
    ("M40", "yard per second squared"),
    ("ANN", "year"),
    ("E57", "zone")
)

ROLES = (
    (u"TRANSPORTATION_CARRIER", u"Tansportation carrier",
     u"Party undertaking or arranging transport of goods between named points."),
    (u"VISITING_ADDRESS", u"Visiting address",
     u"An enterprise physical location where guests are received during set working hours"),
    (u"WAREHOUSE_AND_OR_DEPOT", u"Warehouse or depot",
     u"Industrial department of a company equipped with appropriate equipment and fit-tings in which goods are stored in appropriate conditions."),
    (u"WAREHOUSE_KEEPER", u"Warehouse keeper", u"Party taking responsibility for goods entered into a warehouse."),
    (u"WHOLESALER", u"Wholesaler", u"Seller of articles, often in large quantities, to be retailed by others.")
)

TM = (
    ("533", "Aruba"),
    ("004", "Afghanistan"),
    ("024", "Angola"),
    ("660", "Anguilla"),
    ("248", "Åland Islands"),
    ("008", "Albania"),
    ("020", "Andorra"),
    ("784", "United Arab Emirates"),
    ("032", "Argentina"),
    ("051", "Armenia"),
    ("016", "American Samoa"),
    ("010", "Antarctica"),
    ("260", "French Southern Territories"),
    ("028", "Antigua and Barbuda"),
    ("036", "Australia"),
    ("040", "Austria"),
    ("031", "Azerbaijan"),
    ("108", "Burundi"),
    ("056", "Belgium"),
    ("204", "Benin"),
    ("535", "Bonaire, Sint Eustatius and Saba"),
    ("854", "Burkina Faso"),
    ("050", "Bangladesh"),
    ("100", "Bulgaria"),
    ("048", "Bahrain"),
    ("044", "Bahamas"),
    ("070", "Bosnia and Herzegovina"),
    ("652", "Saint Barthélemy"),
    ("112", "Belarus"),
    ("084", "Belize"),
    ("060", "Bermuda"),
    ("068", "Bolivia, Plurinational State of"),
    ("076", "Brazil"),
    ("052", "Barbados"),
    ("096", "Brunei Darussalam"),
    ("064", "Bhutan"),
    ("074", "Bouvet Island"),
    ("072", "Botswana"),
    ("140", "Central African Republic"),
    ("124", "Canada"),
    ("166", "Cocos (Keeling) Islands"),
    ("756", "Switzerland"),
    ("152", "Chile"),
    ("156", "China"),
    ("384", "Côte d'Ivoire"),
    ("120", "Cameroon"),
    ("180", "Congo, The Democratic Republic of the"),
    ("178", "Congo"),
    ("184", "Cook Islands"),
    ("170", "Colombia"),
    ("174", "Comoros"),
    ("132", "Cabo Verde"),
    ("188", "Costa Rica"),
    ("192", "Cuba"),
    ("531", "Curaçao"),
    ("162", "Christmas Island"),
    ("136", "Cayman Islands"),
    ("196", "Cyprus"),
    ("203", "Czechia"),
    ("276", "Germany"),
    ("262", "Djibouti"),
    ("212", "Dominica"),
    ("208", "Denmark"),
    ("214", "Dominican Republic"),
    ("012", "Algeria"),
    ("218", "Ecuador"),
    ("818", "Egypt"),
    ("232", "Eritrea"),
    ("732", "Western Sahara"),
    ("724", "Spain"),
    ("233", "Estonia"),
    ("231", "Ethiopia"),
    ("246", "Finland"),
    ("242", "Fiji"),
    ("238", "Falkland Islands (Malvinas)"),
    ("250", "France"),
    ("234", "Faroe Islands"),
    ("583", "Micronesia, Federated States of"),
    ("266", "Gabon"),
    ("826", "United Kingdom"),
    ("268", "Georgia"),
    ("831", "Guernsey"),
    ("288", "Ghana"),
    ("292", "Gibraltar"),
    ("324", "Guinea"),
    ("312", "Guadeloupe"),
    ("270", "Gambia"),
    ("624", "Guinea-Bissau"),
    ("226", "Equatorial Guinea"),
    ("300", "Greece"),
    ("308", "Grenada"),
    ("304", "Greenland"),
    ("320", "Guatemala"),
    ("254", "French Guiana"),
    ("316", "Guam"),
    ("328", "Guyana"),
    ("344", "Hong Kong"),
    ("334", "Heard Island and McDonald Islands"),
    ("340", "Honduras"),
    ("191", "Croatia"),
    ("332", "Haiti"),
    ("348", "Hungary"),
    ("360", "Indonesia"),
    ("833", "Isle of Man"),
    ("356", "India"),
    ("086", "British Indian Ocean Territory"),
    ("372", "Ireland"),
    ("364", "Iran, Islamic Republic of"),
    ("368", "Iraq"),
    ("352", "Iceland"),
    ("376", "Israel"),
    ("380", "Italy"),
    ("388", "Jamaica"),
    ("832", "Jersey"),
    ("400", "Jordan"),
    ("392", "Japan"),
    ("398", "Kazakhstan"),
    ("404", "Kenya"),
    ("417", "Kyrgyzstan"),
    ("116", "Cambodia"),
    ("296", "Kiribati"),
    ("659", "Saint Kitts and Nevis"),
    ("410", "Korea, Republic of"),
    ("414", "Kuwait"),
    ("418", "Lao People's Democratic Republic"),
    ("422", "Lebanon"),
    ("430", "Liberia"),
    ("434", "Libya"),
    ("662", "Saint Lucia"),
    ("438", "Liechtenstein"),
    ("144", "Sri Lanka"),
    ("426", "Lesotho"),
    ("440", "Lithuania"),
    ("442", "Luxembourg"),
    ("428", "Latvia"),
    ("446", "Macao"),
    ("663", "Saint Martin (French part)"),
    ("504", "Morocco"),
    ("492", "Monaco"),
    ("498", "Moldova, Republic of"),
    ("450", "Madagascar"),
    ("462", "Maldives"),
    ("484", "Mexico"),
    ("584", "Marshall Islands"),
    ("807", "Macedonia, Republic of"),
    ("466", "Mali"),
    ("470", "Malta"),
    ("104", "Myanmar"),
    ("499", "Montenegro"),
    ("496", "Mongolia"),
    ("580", "Northern Mariana Islands"),
    ("508", "Mozambique"),
    ("478", "Mauritania"),
    ("500", "Montserrat"),
    ("474", "Martinique"),
    ("480", "Mauritius"),
    ("454", "Malawi"),
    ("458", "Malaysia"),
    ("175", "Mayotte"),
    ("516", "Namibia"),
    ("540", "New Caledonia"),
    ("562", "Niger"),
    ("574", "Norfolk Island"),
    ("566", "Nigeria"),
    ("558", "Nicaragua"),
    ("570", "Niue"),
    ("528", "Netherlands"),
    ("578", "Norway"),
    ("524", "Nepal"),
    ("520", "Nauru"),
    ("554", "New Zealand"),
    ("512", "Oman"),
    ("586", "Pakistan"),
    ("591", "Panama"),
    ("612", "Pitcairn"),
    ("604", "Peru"),
    ("608", "Philippines"),
    ("585", "Palau"),
    ("598", "Papua New Guinea"),
    ("616", "Poland"),
    ("630", "Puerto Rico"),
    ("408", "Korea, Democratic People's Republic of"),
    ("620", "Portugal"),
    ("600", "Paraguay"),
    ("275", "Palestine, State of"),
    ("258", "French Polynesia"),
    ("634", "Qatar"),
    ("638", "Réunion"),
    ("642", "Romania"),
    ("643", "Russian Federation"),
    ("646", "Rwanda"),
    ("682", "Saudi Arabia"),
    ("729", "Sudan"),
    ("686", "Senegal"),
    ("702", "Singapore"),
    ("239", "South Georgia and the South Sandwich Islands"),
    ("654", "Saint Helena, Ascension and Tristan da Cunha"),
    ("744", "Svalbard and Jan Mayen"),
    ("090", "Solomon Islands"),
    ("694", "Sierra Leone"),
    ("222", "El Salvador"),
    ("674", "San Marino"),
    ("706", "Somalia"),
    ("666", "Saint Pierre and Miquelon"),
    ("688", "Serbia"),
    ("728", "South Sudan"),
    ("678", "Sao Tome and Principe"),
    ("740", "Suriname"),
    ("703", "Slovakia"),
    ("705", "Slovenia"),
    ("752", "Sweden"),
    ("748", "Swaziland"),
    ("534", "Sint Maarten (Dutch part)"),
    ("690", "Seychelles"),
    ("760", "Syrian Arab Republic"),
    ("796", "Turks and Caicos Islands"),
    ("148", "Chad"),
    ("768", "Togo"),
    ("764", "Thailand"),
    ("762", "Tajikistan"),
    ("772", "Tokelau"),
    ("795", "Turkmenistan"),
    ("626", "Timor-Leste"),
    ("776", "Tonga"),
    ("780", "Trinidad and Tobago"),
    ("788", "Tunisia"),
    ("792", "Turkey"),
    ("798", "Tuvalu"),
    ("158", "Taiwan, Province of China"),
    ("834", "Tanzania, United Republic of"),
    ("800", "Uganda"),
    ("804", "Ukraine"),
    ("581", "United States Minor Outlying Islands"),
    ("858", "Uruguay"),
    ("840", "United States"),
    ("860", "Uzbekistan"),
    ("336", "Holy See (Vatican City State)"),
    ("670", "Saint Vincent and the Grenadines"),
    ("862", "Venezuela, Bolivarian Republic of"),
    ("092", "Virgin Islands, British"),
    ("850", "Virgin Islands, U.S."),
    ("704", "Viet Nam"),
    ("548", "Vanuatu"),
    ("876", "Wallis and Futuna"),
    ("882", "Samoa"),
    ("887", "Yemen"),
    ("710", "South Africa"),
    ("894", "Zambia"),
    ("716", "Zimbabwe"),
)

PACKAGE_TYPES = (
    ("AA", "Intermediate bulk container, rigid plastic"),
    ("AE", "Aerosol"),
    ("AM", "Ampoule"),
    ("BA", "Barrel"),
    ("BBG", "Bag in box"),
    ("BG", "Bag"),
    ("BJ", "Bucket"),
    ("BK", "Basket"),
    ("BO", "Bottle"),
    ("BPG", "Blisterpack"),
    ("BRI", "Brick"),
    ("BX", "Box"),
    ("CG", "Cage"),
    ("CM", "Card"),
    ("CMS", "Clam Shell"),
    ("CNG", "Can"),
    ("CR", "Crate"),
    ("CS", "Case"),
    ("CT", "Carton"),
    ("CU", "Cup/Tub"),
    ("CY", "Cylinder"),
    ("EN", "Envelope"),
    ("GTG", "Gable Top"),
    ("JG", "Jug"),
    ("JR", "Jar"),
    ("MPG", "Multipack"),
    ("NE", "Not packed"),
    ("NT", "Net"),
    ("PB", "Pallet Box"),
    ("PLP", "Peel pack"),
    ("PO", "Pouch"),
    ("PT", "Pot"),
    ("PU", "Tray"),
    ("PUG", "Packed, unspecified"),
    ("PX", "Pallet"),
    ("RK", "Rack"),
    ("RL", "Reel"),
    ("STR", "Stretchwrapped"),
    ("SW", "Shrinkwrapped"),
    ("SY", "Sleeve"),
    ("TU", "Tube"),
    ("WRP", "Wrapper"),
    ("X11", "Banded package"),
    ("ZU", "Flexible Intermediate Bulk Container")
)

BARCODE_TYPES = (
    ("EAN_8", "EAN8"),
    ("EAN_13", "EAN13"),
    ("UPC_A", "UPCA"),
    ("UPC_E", "UPCE"),
    ("ITF_14", "ITF14"),
    ("GS1_128", "GS1128"),
    ("NO_BARCODE", "NULL")
)
