# Generated by Django 2.0.1 on 2018-05-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('short_desc', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('src', models.TextField()),
                ('template', models.TextField()),
                ('rows', models.IntegerField()),
                ('cols', models.IntegerField()),
                ('has_gap', models.BooleanField()),
                ('ratio', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
            ],
        ),
    ]
