# Generated by Django 2.0.1 on 2018-04-16 10:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import organizations.base
import organizations.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BCM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='M2MToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=250, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='MemberOrganisation',
            fields=[
                ('name', models.CharField(help_text='The name of the organization', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created', organizations.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('modified', organizations.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('slug', organizations.fields.SlugField(blank=True, editable=False, help_text='The name in all lowercase, suitable for URL identification', max_length=200, populate_from='name', unique=True)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='member_organisation', serialize=False, to='BCM.Country')),
                ('gs1_prefix_regex', models.CharField(default='.*', max_length=100, verbose_name='GS1_PREFIX_REGEX')),
                ('gs1_logo_path', models.CharField(default='/static/site/logo/gs1-logo.png', max_length=100, verbose_name='GS1_LOGO_PATH')),
                ('gs1_cloud_username', models.CharField(default='', max_length=100, verbose_name='GS1_CLOUD_USERNAME')),
                ('gs1_cloud_secret', models.CharField(default='', max_length=100, verbose_name='GS1_CLOUD_SECRET')),
                ('gs1_could_information_provider_GLN', models.CharField(default='', max_length=100, verbose_name='GS1_CLOUD_IP_GLN')),
            ],
            options={
                'verbose_name': 'Member organisation',
            },
            bases=(organizations.base.UnicodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MemberOrganisationOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', organizations.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('modified', organizations.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'MO admin',
            },
            bases=(organizations.base.UnicodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MemberOrganisationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', organizations.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('modified', organizations.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'MO staff',
                'verbose_name_plural': 'MO staff',
            },
            bases=(organizations.base.UnicodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='', max_length=250, verbose_name='Path')),
                ('definition', models.TextField(verbose_name='Definition')),
                ('ui_mandatory', models.BooleanField(default=True, verbose_name='Is UI mandatory')),
                ('ui_enabled', models.BooleanField(default=True, verbose_name='Is UI enabled')),
                ('ui_read_only', models.BooleanField(default=False, verbose_name='Is UI read only')),
                ('ui_default_callable', models.CharField(blank=True, default='', max_length=100, verbose_name='UI default callable')),
                ('ui_field_validation_callable', models.CharField(blank=True, default='', max_length=100, verbose_name='UI validation callable')),
                ('ui_form_validation_callable', models.CharField(blank=True, default='', max_length=100, verbose_name='UI validation callable')),
                ('ui_label', models.CharField(default='', max_length=100, verbose_name='UI label')),
                ('ui_label_en', models.CharField(default='', max_length=100, null=True, verbose_name='UI label')),
                ('ui_label_cz', models.CharField(default='', max_length=100, null=True, verbose_name='UI label')),
                ('ui_label_de', models.CharField(default='', max_length=100, null=True, verbose_name='UI label')),
                ('ui_label_fr', models.CharField(default='', max_length=100, null=True, verbose_name='UI label')),
                ('ui_label_it', models.CharField(default='', max_length=100, null=True, verbose_name='UI label')),
                ('ui_label_nl', models.CharField(default='', max_length=100, null=True, verbose_name='UI label')),
                ('ui_label_sv', models.CharField(default='', max_length=100, null=True, verbose_name='UI label')),
                ('csv_mandatory', models.BooleanField(default=True, verbose_name='CSV mandatory')),
                ('csv_default_callable', models.CharField(blank=True, default='', max_length=100, verbose_name='CSV default callable')),
                ('csv_field_validation_callable', models.CharField(blank=True, default='', max_length=100, verbose_name='CSV field validation callable')),
                ('csv_form_validation_callable', models.CharField(blank=True, default='', max_length=100, verbose_name='CSV form validation callable')),
                ('codelist_validation', models.CharField(blank=True, default='', max_length=100, verbose_name='codelist validation')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPackaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('image_url', models.URLField(blank=True, max_length=250, verbose_name='Image URL')),
                ('ui_label', models.CharField(default='', max_length=100, verbose_name='UI label')),
                ('ui_label_en', models.CharField(default='', max_length=100, null=True, verbose_name='UI label')),
                ('ui_label_cz', models.CharField(default='', max_length=100, null=True, verbose_name='UI label')),
                ('ui_label_de', models.CharField(default='', max_length=100, null=True, verbose_name='UI label')),
                ('ui_label_fr', models.CharField(default='', max_length=100, null=True, verbose_name='UI label')),
                ('ui_label_it', models.CharField(default='', max_length=100, null=True, verbose_name='UI label')),
                ('ui_label_nl', models.CharField(default='', max_length=100, null=True, verbose_name='UI label')),
                ('ui_label_sv', models.CharField(default='', max_length=100, null=True, verbose_name='UI label')),
                ('ui_description', models.TextField(default='', verbose_name='UI description')),
                ('ui_description_en', models.TextField(default='', null=True, verbose_name='UI description')),
                ('ui_description_cz', models.TextField(default='', null=True, verbose_name='UI description')),
                ('ui_description_de', models.TextField(default='', null=True, verbose_name='UI description')),
                ('ui_description_fr', models.TextField(default='', null=True, verbose_name='UI description')),
                ('ui_description_it', models.TextField(default='', null=True, verbose_name='UI description')),
                ('ui_description_nl', models.TextField(default='', null=True, verbose_name='UI description')),
                ('ui_description_sv', models.TextField(default='', null=True, verbose_name='UI description')),
            ],
            options={
                'verbose_name': 'Product packaging',
                'verbose_name_plural': 'Product packaging',
            },
        ),
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('image_url', models.URLField(blank=True, max_length=250, verbose_name='Image URL')),
                ('ui_label', models.CharField(default='', max_length=100, verbose_name='UI label')),
                ('ui_label_en', models.CharField(default='', max_length=100, null=True, verbose_name='UI label')),
                ('ui_label_cz', models.CharField(default='', max_length=100, null=True, verbose_name='UI label')),
                ('ui_label_de', models.CharField(default='', max_length=100, null=True, verbose_name='UI label')),
                ('ui_label_fr', models.CharField(default='', max_length=100, null=True, verbose_name='UI label')),
                ('ui_label_it', models.CharField(default='', max_length=100, null=True, verbose_name='UI label')),
                ('ui_label_nl', models.CharField(default='', max_length=100, null=True, verbose_name='UI label')),
                ('ui_label_sv', models.CharField(default='', max_length=100, null=True, verbose_name='UI label')),
                ('attributes', models.ManyToManyField(related_name='product_templates', to='member_organisations.ProductAttribute')),
                ('member_organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_templates', to='member_organisations.MemberOrganisation')),
            ],
        ),
    ]
