# Generated by Django 2.0.1 on 2018-04-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_organisations', '0003_auto_20180419_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='ui_label',
        ),
        migrations.RemoveField(
            model_name='productpackaging',
            name='ui_description',
        ),
        migrations.RemoveField(
            model_name='productpackaging',
            name='ui_label',
        ),
        migrations.RemoveField(
            model_name='producttemplate',
            name='ui_label',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='ui_label_i18n',
            field=models.TextField(default='{}', verbose_name='UI label'),
        ),
        migrations.AddField(
            model_name='productpackaging',
            name='ui_description_i18n',
            field=models.TextField(default='{}', verbose_name='UI description'),
        ),
        migrations.AddField(
            model_name='productpackaging',
            name='ui_label_i18n',
            field=models.TextField(default='{}', verbose_name='UI label'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='ui_label_i18n',
            field=models.TextField(default='{}', verbose_name='UI label'),
        ),
    ]
