# Generated by Django 2.0.1 on 2018-04-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_organisations', '0004_auto_20180420_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberorganisation',
            name='login_api_secure',
            field=models.BooleanField(default=False),
        ),
    ]
