# Generated by Django 2.0.1 on 2018-04-28 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member_organisations', '0005_memberorganisation_login_api_secure'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='member_organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes', to='member_organisations.MemberOrganisation'),
        ),
    ]
