# Generated by Django 2.0.1 on 2018-05-04 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_organisations', '0006_attributes_fk_on_MOs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberorganisation',
            old_name='gs1_could_information_provider_GLN',
            new_name='gs1_cloud_ip_gln',
        ),
    ]
