# Generated by Django 2.0.1 on 2018-05-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_organisations', '0006_attributes_fk_on_MOs'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberorganisation',
            name='barcode_credits',
            field=models.BooleanField(default=False),
        ),
    ]
