# Generated by Django 2.0.1 on 2018-05-04 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_organisations', '0007_typo_in_MemberOrganisation'),
        ('member_organisations', '0007_memberorganisation_barcode_credits'),
    ]

    operations = [
    ]
