# Generated by Django 2.0.1 on 2018-05-10 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_organisations', '0009_fixing_packaging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpackaging',
            name='name',
        ),
    ]
