# Generated by Django 2.0.1 on 2018-05-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_organisations', '0010_fixing_packaging_removing_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpackaging',
            name='image_url',
            field=models.TextField(blank=True, max_length=250, verbose_name='Image URL'),
        ),
    ]
