# Generated by Django 2.0.1 on 2018-05-15 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20180515_0957'),
        ('member_organisations', '0011_auto_20180514_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpackaging',
            name='package_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_packaging', to='products.PackageType'),
            preserve_default=False,
        ),
    ]
