# Generated by Django 2.0.1 on 2018-05-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_organisations', '0012_productpackaging_package_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberorganisation',
            name='gs1_logo_height',
            field=models.CharField(default='105px', max_length=20, verbose_name='gs1_logo_height'),
        ),
        migrations.AddField(
            model_name='memberorganisation',
            name='gs1_logo_width',
            field=models.CharField(default='171px', max_length=20, verbose_name='gs1_logo_width'),
        ),
        migrations.AlterField(
            model_name='memberorganisation',
            name='gs1_logo_path',
            field=models.CharField(default='/static/site/logo/gs1-logo.png', max_length=100, verbose_name='gs1_logo_path'),
        ),
    ]
