# Generated by Django 2.0.1 on 2018-05-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_organisations', '0013_auto_20180515_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberorganisation',
            name='gs1_barcode_production_disclaimer',
            field=models.TextField(default='TODO: add text ...', verbose_name='GS1 Barcode Production Disclaimer'),
        ),
        migrations.AddField(
            model_name='memberorganisation',
            name='gs1_cloud_disclaimer',
            field=models.TextField(default='TODO: add text ...', verbose_name='GS1 Cloud Disclaimer'),
        ),
        migrations.AddField(
            model_name='memberorganisation',
            name='gs1_enable_clone_button',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberorganisation',
            name='gs1_enable_cloud_opt_out',
            field=models.BooleanField(default=False),
        ),
    ]
