# Generated by Django 2.0.1 on 2018-05-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_organisations', '0014_auto_20180522_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberorganisation',
            name='gs1_enable_advanced_dashboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberorganisation',
            name='gs1_help_label_1',
            field=models.CharField(default='Training and Resources', max_length=100),
        ),
        migrations.AddField(
            model_name='memberorganisation',
            name='gs1_help_label_2',
            field=models.CharField(default='Support', max_length=100),
        ),
        migrations.AddField(
            model_name='memberorganisation',
            name='gs1_help_label_3',
            field=models.CharField(default='Help', max_length=100),
        ),
        migrations.AddField(
            model_name='memberorganisation',
            name='gs1_help_url_1',
            field=models.CharField(default='/', max_length=100),
        ),
        migrations.AddField(
            model_name='memberorganisation',
            name='gs1_help_url_2',
            field=models.CharField(default='/', max_length=100),
        ),
        migrations.AddField(
            model_name='memberorganisation',
            name='gs1_help_url_3',
            field=models.CharField(default='/', max_length=100),
        ),
    ]
