# Generated by Django 2.0.1 on 2018-05-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_organisations', '0015_auto_20180526_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberorganisation',
            name='gs1_enable_user_settings',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='memberorganisation',
            name='gs1_cloud_ip_gln',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='GS1_CLOUD_IP_GLN'),
        ),
        migrations.AlterField(
            model_name='memberorganisation',
            name='gs1_cloud_secret',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='GS1_CLOUD_SECRET'),
        ),
        migrations.AlterField(
            model_name='memberorganisation',
            name='gs1_cloud_username',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='GS1_CLOUD_USERNAME'),
        ),
    ]
