# Generated by Django 2.0.1 on 2018-06-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_organisations', '0017_memberorganisation_gs1_enable_import_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberorganisation',
            name='gs1_terms_enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberorganisation',
            name='gs1_terms_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberorganisation',
            name='gs1_terms_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
