# Generated by Django 2.0.1 on 2018-06-15 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('member_organisations', '0019_auto_20180609_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberOrganisationRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('member_organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberorganisation_relations', to='member_organisations.MemberOrganisation')),
            ],
        ),
    ]
