# Generated by Django 2.0.1 on 2018-06-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_organisations', '0020_memberorganisationrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberorganisation',
            name='login_api_auth_only',
            field=models.BooleanField(default=False),
        ),
    ]
