# Generated by Django 2.0.1 on 2018-06-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_organisations', '0021_memberorganisation_login_api_auth_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberorganisation',
            name='show_leading_digit',
            field=models.BooleanField(default=True),
        ),
    ]
