# Generated by Django 2.0.1 on 2018-06-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_organisations', '0022_memberorganisation_show_leading_digit'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberorganisation',
            name='display_prefix_as_range',
            field=models.BooleanField(default=True),
        ),
    ]
