# Generated by Django 2.0.1 on 2018-06-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_organisations', '0023_memberorganisation_display_prefix_as_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberorganisation',
            name='gs1_logo_url',
            field=models.CharField(default='/', max_length=100),
        ),
        migrations.AddField(
            model_name='memberorganisation',
            name='gs1_logout_url',
            field=models.CharField(default='/', max_length=100),
        ),
    ]
