# Generated by Django 2.0.1 on 2018-06-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_organisations', '0024_auto_20180630_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberorganisation',
            name='display_account_info',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='memberorganisation',
            name='display_prefix_info',
            field=models.BooleanField(default=True),
        ),
    ]
