# Generated by Django 2.0.1 on 2018-08-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_organisations', '0028_auto_20180712_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberorganisation',
            name='gs1_disable_hiearchy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberorganisation',
            name='gs1_disable_pdf_labels',
            field=models.BooleanField(default=False),
        ),
    ]
