# Generated by Django 2.0.1 on 2018-08-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_organisations', '0029_labels and hiearchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberorganisation',
            name='gs1_enable_pdf_print_summary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='memberorganisation',
            name='gs1_disable_pdf_labels',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
