# Generated by Django 2.0.1 on 2018-04-16 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import organizations.base
import organizations.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BCM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the organization', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created', organizations.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('modified', organizations.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('slug', organizations.fields.SlugField(blank=True, editable=False, help_text='The name in all lowercase, suitable for URL identification', max_length=200, populate_from='name', unique=True)),
                ('uuid', models.CharField(max_length=50, unique=True)),
                ('company', models.CharField(default='', max_length=100)),
                ('street1', models.CharField(default='', max_length=100)),
                ('street2', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('zip', models.CharField(default='', max_length=20)),
                ('phone', models.CharField(default='', max_length=20)),
                ('gln', models.CharField(default='', max_length=13)),
                ('vat', models.CharField(default='', max_length=12)),
                ('credit_points_balance', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('prefix_override', models.CharField(default='', max_length=100)),
                ('gln_capability', models.BooleanField(default=False)),
                ('country', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='BCM.Country')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
            bases=(organizations.base.UnicodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CompanyOrganisationOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', organizations.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('modified', organizations.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='company_organisations.CompanyOrganisation')),
            ],
            options={
                'verbose_name': 'Company admin',
            },
            bases=(organizations.base.UnicodeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CompanyOrganisationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', organizations.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('modified', organizations.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_users', to='company_organisations.CompanyOrganisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_organisations_companyorganisationuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company user',
            },
            bases=(organizations.base.UnicodeMixin, models.Model),
        ),
        migrations.AddField(
            model_name='companyorganisationowner',
            name='organization_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company_organisations.CompanyOrganisationUser'),
        ),
    ]
