# Generated by Django 2.0.1 on 2018-07-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_organisations', '0002_auto_20180416_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyorganisation',
            name='state',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='companyorganisation',
            name='street2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyorganisation',
            name='vat',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
