# Generated by Django 2.0.1 on 2018-07-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_organisations', '0003_auto_20180703_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyorganisation',
            name='company',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyorganisation',
            name='name',
            field=models.CharField(blank=True, help_text='The name of the organization', max_length=200),
        ),
        migrations.AlterField(
            model_name='companyorganisation',
            name='prefix_override',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
