# Generated by Django 2.0.1 on 2018-04-16 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member_organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company_organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryOfOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='DimensionUOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(default='', max_length=20)),
                ('abbr', models.CharField(default='', max_length=10)),
                ('code', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=5, unique=True)),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='NetContentUOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(default='', max_length=30)),
                ('abbr', models.CharField(default='', max_length=10)),
                ('code', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PackageLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='', max_length=100)),
                ('unit_descriptor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=100)),
                ('code', models.CharField(default='', max_length=10)),
                ('image_path', models.CharField(default='', max_length=70)),
                ('description', models.TextField(default='')),
                ('ui_enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtin', models.CharField(blank=True, db_index=True, default='', max_length=14, unique=True)),
                ('gs1_company_prefix', models.CharField(blank=True, db_index=True, default='', max_length=75)),
                ('gln_of_information_provider', models.CharField(max_length=75, null=True)),
                ('category', models.CharField(max_length=75, null=True)),
                ('label_description', models.CharField(max_length=500, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('sku', models.CharField(max_length=75, null=True)),
                ('brand', models.CharField(max_length=75, null=True)),
                ('sub_brand', models.CharField(max_length=75, null=True)),
                ('functional_name', models.CharField(max_length=75, null=True)),
                ('variant', models.CharField(max_length=75, null=True)),
                ('image', models.CharField(max_length=255, null=True)),
                ('depth', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('net_content', models.CharField(max_length=10, null=True)),
                ('gross_weight', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('net_weight', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('bar_placement', models.CharField(max_length=50, null=True)),
                ('point_of_sale', models.CharField(max_length=75, null=True)),
                ('website_url', models.CharField(max_length=256, null=True)),
                ('is_bunit', models.BooleanField(default=False)),
                ('is_cunit', models.BooleanField(default=False)),
                ('is_dunit', models.BooleanField(default=False)),
                ('is_vunit', models.BooleanField(default=False)),
                ('is_iunit', models.BooleanField(default=False)),
                ('is_ounit', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(null=True)),
                ('eff_date', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('discontinued_date', models.DateTimeField(null=True)),
                ('name_of_information_provider', models.CharField(max_length=100, null=True)),
                ('gs1_cloud_state', models.CharField(default='INACTIVE', max_length=75)),
                ('mark', models.IntegerField(default=0)),
                ('company_organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='company_organisations.CompanyOrganisation')),
                ('country_of_origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.CountryOfOrigin')),
                ('depth_uom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_depth_uom', to='products.DimensionUOM')),
            ],
        ),
        migrations.CreateModel(
            name='SubProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.Product')),
                ('sub_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_products', to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='TargetMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('market', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='WeightUOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(default='', max_length=20)),
                ('abbr', models.CharField(default='', max_length=10)),
                ('code', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='gross_weight_uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_grossweight_uom', to='products.WeightUOM'),
        ),
        migrations.AddField(
            model_name='product',
            name='height_uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_height_uom', to='products.DimensionUOM'),
        ),
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Language'),
        ),
        migrations.AddField(
            model_name='product',
            name='member_organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='member_organisations.MemberOrganisation'),
        ),
        migrations.AddField(
            model_name='product',
            name='net_content_uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_netcontent_uom', to='products.NetContentUOM'),
        ),
        migrations.AddField(
            model_name='product',
            name='net_weight_uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_netweight_uom', to='products.WeightUOM'),
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='package_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.PackageLevel'),
        ),
        migrations.AddField(
            model_name='product',
            name='package_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.PackageType'),
        ),
        migrations.AddField(
            model_name='product',
            name='target_market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.TargetMarket'),
        ),
        migrations.AddField(
            model_name='product',
            name='width_uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_width_uom', to='products.DimensionUOM'),
        ),
        migrations.AlterUniqueTogether(
            name='subproduct',
            unique_together={('product', 'sub_product')},
        ),
    ]
