# Generated by Django 2.0.1 on 2018-04-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180419_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='functional_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='label_description',
        ),
        migrations.AddField(
            model_name='product',
            name='brand_i18n',
            field=models.TextField(default='{}', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='company_i18n',
            field=models.TextField(default='{}', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_i18n',
            field=models.TextField(default='{}', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='functional_name_i18n',
            field=models.TextField(default='{}', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_i18n',
            field=models.TextField(default='{}', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='label_description_i18n',
            field=models.TextField(default='{}', null=True),
        ),
    ]
