# Generated by Django 2.0.1 on 2018-04-23 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180420_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='GtinTargetMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtin', models.CharField(blank=True, db_index=True, default='', max_length=14)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.Product')),
                ('target_market', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.TargetMarket')),
            ],
        ),
        migrations.AlterField(
            model_name='gtintargetmarket',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='product', to='products.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='gtintargetmarket',
            unique_together={('gtin', 'target_market')},
        ),
    ]
