# Generated by Django 2.0.1 on 2018-04-24 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member_organisations', '0004_auto_20180420_0345'),
        ('products', '0006_auto_20180424_1231'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='packagetype',
            unique_together={('member_organisation', 'code')},
        ),
    ]
