# Generated by Django 2.0.1 on 2018-04-24 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180424_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtintargetmarket',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gtin_target_market', to='products.Product'),
        ),
    ]
