# Generated by Django 2.0.1 on 2018-04-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180424_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='company_i18n',
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
