# Generated by Django 2.0.1 on 2018-04-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_fixing_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_trade_item_id_type',
            field=models.CharField(default='SUPPLIER_ASSIGNED', max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='bar_type',
            field=models.CharField(default='EAN13', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='communication_channel_code',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='communication_value',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='descriptive_size',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='end_availability',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_price_on_pack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='last_change',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_gln',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='returnable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='size_code',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='start_availability',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='type_of_information',
            field=models.CharField(default='PRODUCT_IMAGE', max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_of_information_provider',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
