# Generated by Django 2.0.1 on 2018-06-15 12:46

from django.db import migrations
from itertools import chain
import json
from django.db import migrations, models


def get_all_uom_instances(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    NetContentUOM = apps.get_model('products', 'NetContentUOM')
    DimensionUOM = apps.get_model('products', 'DimensionUOM')
    WeightUOM = apps.get_model('products', 'WeightUOM')

    all_instances = chain(
        NetContentUOM.objects.using(db_alias).all(),
        DimensionUOM.objects.using(db_alias).all(),
        WeightUOM.objects.using(db_alias).all(),
    )

    return all_instances


def forwards_func(apps, schema_editor):
    for item in get_all_uom_instances(apps, schema_editor):
        item.uom_i18n = json.dumps({'en': item.uom_i18n})
        item.save()


def reverse_func(apps, schema_editor):
    for item in get_all_uom_instances(apps, schema_editor):
        item.uom_i18n = json.loads(item.uom_i18n).get('en', '')
        item.save()


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0012_auto_20180515_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimensionuom',
            old_name='uom',
            new_name='uom_i18n',
        ),
        migrations.RenameField(
            model_name='netcontentuom',
            old_name='uom',
            new_name='uom_i18n',
        ),
        migrations.RenameField(
            model_name='weightuom',
            old_name='uom',
            new_name='uom_i18n',
        ),

        migrations.AlterField(
            model_name='dimensionuom',
            name='uom_i18n',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='netcontentuom',
            name='uom_i18n',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='weightuom',
            name='uom_i18n',
            field=models.CharField(default='', max_length=200),
        ),

        migrations.RunPython(forwards_func, reverse_func),
    ]
